### ISSUE TITLE
Darker background for white player name in review mode

### ISSUE THREAD

**Issue by bdrose** [online-go/online-go.com#1005]
**Is your feature request related to a problem? Please describe.**
When reviewing a game, the light background color for the white player name makes the name and rank difficult to see.

**Describe the solution you'd like**
A darker background for review mode around the players name and rank for the white player.
Perhaps making the white player background a solid dark gray and the black player solid black to distinguish the white and black players.

**Additional context**
![image](https://user-images.githubusercontent.com/30013849/70190550-d1a26e00-16bb-11ea-8ae9-e1c885d1ffc3.png)

**Comment by GreenAsJade** [comment]
I totally agree.  This is particularly a nuisance when streamers show the name boxes on their own screens in different places, which they seem to love doing.

![Screen Shot 2019-12-05 at 3 05 29 pm (3)](https://user-images.githubusercontent.com/61894/70204511-c6f5e080-1770-11ea-8a80-ceefe3fbdeac.png)

Here we see the chat on Dwyrin's stream having trouble understanding who is black and white.

**Comment by BHydden** [comment]
Currently the boxes match, as in they have the lightest portion at the top and the darkest at the bottom... what if we just flipped the gradient for the white one, so that move nameplates have a medium grey at the top that the name sits on, and then they both fall to their respective colour; black or white...

crude mockup:
![image](https://user-images.githubusercontent.com/28991649/70204923-07a02a80-176e-11ea-94ee-be37f6d609fd.png)

**Comment by GreenAsJade** [comment]
I did something like that BHydden in the proposed PR, thanks for the idea.
