### ISSUE TITLE
Create new games by sending URLs

### ISSUE THREAD

**Issue by aaronslin** [online-go/online-go.com#1023]
lichess has a great feature that my friends and I use frequently: when we want to play a game, we create a lichess link and paste it in a group chat, and the first person to join becomes the opponent.

**Comment by anoek** [comment]
That's a great idea

**Comment by BHydden** [comment]
See past forum discussion on this (or similar) idea [here](https://forums.online-go.com/t/invite-new-users/515?u=bhydden) and, more recently, [here](https://forums.online-go.com/t/invitation-to-game-or-open-challenge-as-a-url/23366?u=bhydden). :)

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.

**Comment by benjaminpjones** [comment]
Bumping this one because I think it would be nice.  I don't think we have the infrastructure to do it like lichess (no login needed) but the login flow is fast enough that I think we could do it in a way that makes it easy for new users.

Something like:

1. Current user generates a link-based challenge
2. Another user accepts the challenge by going to the link
3. If the user does not have an account, they are shown the registration screen then immediately redirected to the game after registering.

As far as backend changes I'd have to do a little digging.  It seems like there are already challenge ids for open challenges, so the routes can be set accordingly. Bigger question is I'm not sure if there's a way to have an open challenge that doesn't also show up on the **Play** page.

**Comment by benjaminpjones** [comment]
@GreenAsJade would you say this one is resolved via challenge links?

**Comment by GreenAsJade** [comment]
Yeah for sure
