### ISSUE TITLE
Custom Settings for Group Ladders

### ISSUE THREAD

**Issue by yewang** [online-go/online-go.com#1042]
**Describe the solution you'd like**
Allow groups to customize the settings/rules of their ladders.

Various settings that could be customized:

* Time settings
* Game play rules (e.g., Japanese, Chinese, AGA, New Zealand, etc.)
* Whether analysis is enabled
* Number of active challenges
* Handicap settings?

**Additional context**

Discussion on the forums:
https://forums.online-go.com/t/allow-custom-settings-for-group-ladders/24796

**Comment by koshogs** [comment]
As mentioned in the forums, this could be a great feature for OGS but I think it would be wise to deal with this: https://github.com/online-go/online-go.com/issues/1041 first so that the new feature makes a good first impression.

**Comment by yewang** [comment]
I forgot about board size customization. OGS currently supports only 9x9, 13x13, and 19x19, but there seems to at least be some interest for a 25x25 ladder

https://forums.online-go.com/t/can-i-create-a-ladder-with-bigger-than-19x19-boards/30695

**Comment by benjaminpjones** [comment]
Re-opening as this seems like a popular feature request (8 thumbs and forums threads)

**Comment by dexonsmith** [comment]
FYI, #2541 will land fairly soon (I think?), allowing groups to configure the rules for their ladders. In the future, we could use the same scaffolding to add other ladder configuration, but for now @anoek and I thought it was best to start with just one thing and get that working. I picked "rules".

> Game play rules (e.g., Japanese, Chinese, AGA, New Zealand, etc.)

When that PR lands, this issue will close, having only completed the "rules" part of the request.

But I filed #2551, #2552, #2553, #2554, and #2555 to track the other feature requests separately. Some of them require more/less work than others (in some cases due to extra backend plumbing), so IMO it's best to land them incrementally.
