### ISSUE TITLE
Blitz 10s time controls result in saying "10" each move

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#11]
### Summary

When playing blitz with 10 second periods, after you make your move, the voice says "10" when resetting the clock. If possible it shouldn't say your time left after you've moved.

### Environment

 * Operating system: Windows 10
 * Browser: Chrome
 * Browser Version:

### Steps To Reproduce:

Start a blitz game, no main time, 5-10 second periods, play and make your move.

**Comment by lemurek** [comment]
I've been working on a fix for the issue, and managed to clean-up the code significantly - to refresh the countdown only on opponents turn. However to my surprise the problem still persisted. I decided to print out the clock updates I'm seeing, and there is some awkwardness in the engine.playerToMove() behaviour. 

![screen shot 2017-02-25 at 19 35 12](https://cloud.githubusercontent.com/assets/12175058/23334180/90c34d02-fb91-11e6-93a0-a8abb0a4ef9d.png)

The print out may be obscure, but let me try to explain. Current player is 500, and opponent is 501, byo-yomi was set to 6 seconds.

1. **sound_to_play: 5**  
says 'Five'
2. **sound_to_play: 4**  
says 'Four', end of turn
3. **sound_to_play: 6**  
silent because it's opponents turn (resets last sound played)
4. **sound_to_play: 6**  
silent nothing because it's opponents turn (notice last sound played reset)
5. **sound_to_play: 6**  
This is the weird part, where for 1 clock update it is 'my' turn again 
6. **sound_to_play: 6**  
silent

I could hack it around, but it seems that fixing it on a countdown level is not the correct solution. Is there a good reason why engine 'thinks' it's my turn for a split second after the move was made?

**Comment by roy7** [comment]
Maybe look at the behavior of active_game vs move events. Once you move, you'll get 2 events back (not always in same order). A move telling you a move was made, and an active_game telling you new game state and whose turn it is and so on. There is also a clock event any time clock info changes for a game, that is also separate from the other two events.

Perhaps when you make the move it resets the clock, so timer changes and new sound needs to go off, before active_game tells you it is your turn. In that case we might need a client side toggle of some sort, set it when you make a move and check that for sound regardless of active_game, then turn sounds back on next time active_game says it is your turn? Or clear the "i made a move" flag as soon as the next active_game arrives?

**Comment by lemurek** [comment]
If it's a correct behaviour I can easily suppress that single event from being said out loud. My concern was more around if the set of events I'm seeing is actually intended.

**Comment by roy7** [comment]
Only @anoek could answer that for sure. Server black magic.

**Comment by anoek** [comment]
@roy7 So we don't actually use `active_game` in this case, on the UI side that's purely used to control the little turn notifier in the upper right. When dealing with bots we use it because that also tells you what game you need to go load and make a move on, honestly with your persistence work we could probably get smart and only use that to trigger when to load a game if it's not already loaded, otherwise just pay attention to the `move` events.

@lemurek Good find, as you suspect, I don't think we should be setting last sound played when we don't play a sound. And of course, whenever one asks "Is there a good reason...", the answer is usually "probably not". My guess is that the reason for this lies here: https://github.com/online-go/online-go.com/blob/devel/src/lib/ogs-goban/GoEngine.ts#L764 where we call some callbacks before https://github.com/online-go/online-go.com/blob/devel/src/lib/ogs-goban/GoEngine.ts#L777 where we set the opponent. It might be safe to move that callback down below the swap, but would definitely want to do some digging to figure out if that is going to break anything.

**Comment by lemurek** [comment]
In the end I managed to keep the countdown behaving by playing the sound only when the counter goes down. Actually the pull request I've submitted might be slightly overcomplicating stuff by attempting to save the '10' in byo-yomi using opponents turn to refresh the played_sound counter to 99. 

The solution will be much simpler if we sacrifice the '10' and only pronounce counter as it decreases. What do you think @anoek ?

**Comment by roy7** [comment]
@anoek Ooo, I was thinking when I first noticed the lag between move and active_game that maybe I should just start the bot thinking. I came up with a work around plan, but is it safe to just ignore active_game for games already connected and simply do everything based on move? I was worried what if move comes in, active_game is 10 seconds later, and I submit a move before the active_game arrives. Will the server reject it if it thinks it is still on the prior move? Or can I assume once I get opponent's move event it is safe for me to move immediately?

This would eliminate move/active game race conditions. I'd just move any time I receive opponent move, and if I get an unexpected gamedata event I can either try to salvage (send any missing move to the bot) or just restart the bot in that case.

**Comment by roy7** [comment]
@lemurek That'd better than saying ten every time you move, which is a bit of an annoyance. But in a perfect world it'd say ten the moment your turn started (really is your turn, not a fake turn start).

**Comment by lemurek** [comment]
Anyway, submitted both approaches as fix propositions:

**Try to detect turn changes + pronounce on decrease + extra complications to kill the extra event**  
https://github.com/online-go/online-go.com/pull/15

**Ignore the '10' and simply pronounce on decrease**  
https://github.com/online-go/online-go.com/pull/18

Over and out :)
