### ISSUE TITLE
English language selected, but the board's y-coordination in Chinese

### ISSUE THREAD

**Issue by phil-flex** [online-go/online-go.com#1119]
**Describe the bug**
English language selected by board y-coordination in Chinese

**To Reproduce**
1. Go to 'Settings', select "English" language, and select "Broad labelling" to "1-1"
2. Click to view any game in OGS
3. Check the y-coordination still in Chinese

**Expected behavior**
When board labeling selected "1-1" what I expected are in 1-1 in both coordinations

I suggest that x and y should also use 1,2,3,4,5...

**Screenshots**
![image](https://user-images.githubusercontent.com/34325924/80296062-9e679500-87aa-11ea-97a8-e826448af101.png)

![image](https://user-images.githubusercontent.com/34325924/80296073-b17a6500-87aa-11ea-89c6-1ceb5018e6f1.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome 
 - Version 81

**Comment by BHydden** [comment]
Yeah, this label should probably be reworded. It is working correctly but I can see why you were confused as it is not very clear. The only preferences we have is:
A1: X-axis will be A-J on 9x9 and A-T on 19x19, Y-axis will be English numbers
1-1: X-axis will be English numbers, Y-axis will be Chinese/Japanese numbers

none of these are affected by the language selected

**Comment by runarberg** [comment]
I noticed that the direction is reversed between A1 and 1-1.

![1-1 notation board](https://user-images.githubusercontent.com/3984600/80523096-6430fb80-8942-11ea-935a-22c836805afb.png) ![A1 notation board](https://user-images.githubusercontent.com/3984600/80523271-a5c1a680-8942-11ea-8362-0290405a34b3.png)

Notice above how the last stone White (kata-bot 7d) played before Black (masamune_40b 9d) resigned is on J14 using A1 notation, but on 9-6 using the 1-1 notation.

Is this intentional, if so shouldn’t we be translating between coordinate notation in the chat? E.g. opponent—uses A1 style—says: “H7 kills”, while I—using 1-1 style—see “8-13 kills” or “８の十三 kills”?
