### ISSUE TITLE
Ranked games are possible with unfair handicap

### ISSUE THREAD

**Issue by mark5000** [online-go/online-go.com#113]
### Summary

From the Open Challenge menu, it is possible to create a ranked game with handicap manually set in your favor. 

### Environment

 * All operating systems and browsers

### Steps To Reproduce:

1. Create a custom game from the Open Challenge menu.
2. See that the boxes for ranked and enable handicap can be checked at the same time that handicap is manually set.
3. See that the boxes for ranked and enable handicap can be checked at the same time that color is manually set.

### Additional Information:

This bug has resulted in games where, for example, an 8k takes 3 handicap and black against a 15k player on 9x9. PM for further details if necessary.

**Comment by anoek** [comment]
Note that while this is super lame, and should probably be prevented, the rating points "earned" or lost by such a game should be very close to zero

**Comment by juanchodepisa** [comment]
"Unfair" handicap should be possible to an extent, IMO. For example if there's a 6 stone diff between the players but they decide the weaker player only wants to take 3 handicap stones.

Refusing to allow such a ranked game would be somewhat inconsistent, since both a 6 stone handicap and an even game are possible, and what I just described is in between.

I think, however, there should be a maximum limit to the combined formula of real_diff = rank_diff - handicap_stones (assuming that the handicap is taken by the weaker player, otherwise handicap_stones would have a negative value in this formula) for ranked games.

**Comment by anoek** [comment]
Yep, the magic number is 9 for the rank difference, here it was 10 though, hence the bug.

**Comment by mark5000** [comment]
The situation where a player wants to have less handicap in a rated game should be permissible.

The situation where a player wants to have more handicap in a rated game is questionable, but personally I'm ok with it. A change here may require more discussion.

The situation where the stronger player wants to have the handicap in a rated game is the situation I feel is patently unfair and should be disallowed.

**Comment by anoek** [comment]
Rating part of this is done on the server side. I think I'm not going to worry too much about trying to disallow a stronger opponent from taking a handicap because the potential for abuse of that behavior should go away with automatch.

**Comment by mark5000** [comment]
This problem still exists. See https://online-go.com/game/9130754
