### ISSUE TITLE
/groupadmin/<group_id> from mail notification throws 404

### ISSUE THREAD

**Issue by soerface** [online-go/online-go.com#1142]
**Describe the bug**
As a group admin, you may receive an email about someone requesting to join your group. The email contains this text:

> Visit https://online-go.com/groupadmin/<group_id>  to accept or reject this request

This link throws an **HTTP 404 Not found**. A valid link to the group would be `/group/<group_id>`, though it is not possible from this page to accept or reject the request. Accepting or rejecting seems to be only possible through the on-site notifications.

**To Reproduce**
1. Be a group owner of a closed group
2. Let someone else request a membership for this group
3. Read your mails

**Expected behavior**
I expect that the mail contains a valid link where I can accept or reject the request.

**Comment by timhunt** [comment]
I am seeing this problem too - it is a problem because someone wants to join my group, and I cannot let them in. (User with id 433764 trying to join https://online-go.com/group/4785 if you want a real example to investigate. If, during your testing, you approve them joining the group, that is not a problem.)
