### ISSUE TITLE
Playing a stone in Joseki 'Play Mode' immediately after resetting Joseki

### ISSUE THREAD

**Issue by ofekih** [online-go/online-go.com#1151]
**Describe the bug**
If you go to the Joseki explorer, and play a move right after resetting the Joseki sequence, it causes weird errors.

**To Reproduce**
As above, just see this video:
[https://www.loom.com/share/af35f7fa811b49bdbcb596c9a11a0d8a](https://www.loom.com/share/af35f7fa811b49bdbcb596c9a11a0d8a)

Also happens whenever a move is played too quickly, even if it isn't the first move. When it's not the first move, people probably encounter it less often (since they have to think about their next moves)

**Expected behavior**
This doesn't happen

**Comment by ofekih** [comment]
Feel free to assign this issue to me

**Comment by Xandaros** [comment]
This also happens if you just place a stone right away - before the suggestions come up. (Not in play mode. I didn't even know that was a thing)

![](http://tcp.st/ab7b0.png)

Note how the position is labelled "Empty board" and it shows suggestions as if it were, in fact, an empty board. (Even on the stone!)
