### ISSUE TITLE
Mekura-go (one colour go)

### ISSUE THREAD

**Issue by kerekecuk** [online-go/online-go.com#1184]
Sometimes I want to play one colour go with my friends. 

Maybe other players wwill want to play in this mode.

But now there are no gaming sites with this feature.

https://senseis.xmp.net/?OneColourGo

My point of view:
 * In game settings player can set "disable analysis" and after that will be allow new setting: "One colour mode".
 * Goban canvas prints a one color stones  for both players.
 * In sgf export or in the alalyze tool colors will be normal, white and black.

![bb86f902a7251331a88021f90248c4b8](https://user-images.githubusercontent.com/59731982/85940569-65cd6e80-b947-11ea-8c6a-c1312beacc33.png)
![one colour go](https://user-images.githubusercontent.com/59731982/85940683-002db200-b948-11ea-8ab8-0f59765c3e48.PNG)

**Comment by stephancurran** [comment]
This is a cool idea. I'd make one change to your suggested flow - rather than adding a new setting after _Disable Analysis_, add two options to the _Your Color_ drop-down: _One Color (Black)_ and _One Color (White)_. That doesn't allow for your opponent to view the stones in a different colour though. Also, this should probably not be available for ranked games.

If you're interested in a workaround, use the drop-down in the top-right of the screen to access the Theme menu, select the plain stones (the leftmost in each row), and click the coloured box. The other player would have to do the same, of course.
![theme](https://user-images.githubusercontent.com/494175/89129203-be21fe00-d4fb-11ea-94db-f86b54272577.png)
