### ISSUE TITLE
What's the best way to look for issues to get started helping with? [question]

### ISSUE THREAD

**Issue by rileylark** [online-go/online-go.com#1191]
Howdy,

I'm brand new to go and OGS but an experienced software developer and I'm interested in trying to help! I've read the developer introduction and a few other docs, and now I'm looking for the best way to actually dig in a little bit.

I'm looking at the [issues marked "priority"](https://github.com/online-go/online-go.com/projects/2?card_filter_query=label%3Apriority) as a place to start - is that a productive place to start? Is there a list of bugs or tiny features that are well defined that y'all would point me towards?

**Comment by anoek** [comment]
A fair question, and unfortunately I don't have a great organized answer for you. The priority items are probably not what you want to tackle first though, simply because if they're still open they probably have a notable amount of work to do, so probably not great first items. I would start by looking at the open issues and looking for smallish sounding stuff that interests you.

**Comment by anoek** [comment]
Also, thanks for being interested in jumping in and helping out!

**Comment by BHydden** [comment]
Cosmetic improvements, or small features you personally desire to see implemented to improve the site, are usually great places to start 👍
