### ISSUE TITLE
AI suggests playing on a stone

### ISSUE THREAD

**Issue by soerface** [online-go/online-go.com#1196]
**Describe the bug**
I've observed a strange behavior in the AI review. It suggests playing on a field that is already occupied.

**To Reproduce**
1. Go to https://online-go.com/game/21571910 
2. Go to analysis, move 245
3. Click on the suggested AI move on D6
4. Suggested moves 2 - 8 are normal and expected
5. Move 9 suggestion is to play on Q19, but there is already a black stone

It also happens on other moves later on, e.g. 264 / D6,  249 / E12, 251 / E12 and more

**Expected behavior**
Either no move 9, or a playable suggestion. Maybe the AI want's to tell me it would pass?

**Screenshots**
![image](https://user-images.githubusercontent.com/967243/87033171-080e1180-c1e6-11ea-91e0-2f0365f315ec.png)

**Desktop (please complete the following information):**
 - Chromium Version 83.0.4103.116 (Official Build) snap (64-bit)

**Comment by anoek** [comment]
I finally figured out what was going on here, we were getting a `pass` string and parsing it with the wrong coordinate parser because of bad reasons. The bad parsing was parsing out the 'pa' part of the string, which happens to be 'Q19' in normal coordinate land. So long story short, every time katago would give us a pass recommendation we'd be displaying it as 'Q19'. Whoops.

This is fixed on the backend (or will be very shortly at anyrate).
