### ISSUE TITLE
Komi behaving weirdly in certain games

### ISSUE THREAD

**Issue by RubyMineshaft** [online-go/online-go.com#1240]
**Describe the bug**
Komi seems to be behaving weirdly in a small subset of 9x9 games

**Screenshots**

https://online-go.com/game/27578385
![Screen Shot 2020-10-16 at 11 53 46 PM](https://user-images.githubusercontent.com/42720842/96328659-1baded00-100b-11eb-914c-faddcfe46174.png)

https://online-go.com/game/27578346
![Screen Shot 2020-10-16 at 11 58 22 PM](https://user-images.githubusercontent.com/42720842/96328709-9aa32580-100b-11eb-8450-5cc919131b6d.png)
![Screen Shot 2020-10-16 at 11 58 38 PM](https://user-images.githubusercontent.com/42720842/96328710-9bd45280-100b-11eb-9764-db7723b4ed56.png)

**Comment by benjaminpjones** [comment]
Welcome to the wonderful world of floating point arithmetic :) The issue here is that 0.53 cannot be represented exactly in binary floating point ([SO: Is floating point math broken?](https://stackoverflow.com/questions/588004/is-floating-point-math-broken)).

You can reproduce this on other board sizes as well, but it's a little hit or miss depending on what the final scores are.

<img width="896" alt="Screen Shot 2020-10-25 at 11 57 27 AM" src="https://user-images.githubusercontent.com/25233703/97112369-46a6d980-16ba-11eb-813a-4d6ff398d33c.png">

The practical solution would be to update [Game.tsx](https://github.com/online-go/online-go.com/blob/5105fcd0d1923b2cd1f02321fb6cc4e1e0fcfe14/src/views/Game/Game.tsx#L2509) to truncate `outcome` when it is shown to the user.  I don't want to take all the low hanging fruit but here is a [hint](https://stackoverflow.com/questions/4256030/limit-the-amount-of-number-shown-after-a-decimal-place-in-javascript) for anyone who wants to tackle this!

**Comment by benjaminpjones** [comment]
The **Game History** table (in [User.tsx](https://github.com/online-go/online-go.com/blob/02e083b78de56155d588c165a41b7c03eb079a1a/src/views/User/User.tsx) and [`getGameResultText`](https://github.com/online-go/online-go.com/blob/02e083b78de56155d588c165a41b7c03eb079a1a/src/lib/misc.ts#L194)) should probably also be fixed at the same time: 

<img width="809" alt="Screen Shot 2020-10-26 at 8 58 04 PM" src="https://user-images.githubusercontent.com/25233703/97244037-f9b42780-17cd-11eb-9553-f8008a37a723.png">

Of course the real fix would be to only allow komi that ends in .5 or .0, which don't have these issues...

**Comment by BHydden** [comment]
> Of course the real fix would be to only allow komi that ends in .5 or .0, which don't have these issues...

surely this should already be the case???

**Comment by benjaminpjones** [comment]
Nope- The game settings dialog allows one to specify not one, but TWO digits of precision!
