### ISSUE TITLE
Enhancement: Use ΔScore in calculation of top 3 moves for handicap games

### ISSUE THREAD

**Issue by benjaminpjones** [online-go/online-go.com#1343]
I believe score is a better indicator of major events in the game, but this is especially prominent in handicap games.  See discussion at [Top 3 Moves: Score a Better Metric?](https://forums.online-go.com/t/top-3-moves-score-a-better-metric/32702/9).  I assume this would be a backend change, but if I'm wrong, please let me know!

**Proposed Solution**
For handicap games, instead of the top changes in win rate, display the top changes in score.  I think using win rate still has merit in even games (particularly high level ones).

**Comment by anoek** [comment]
I think this could be prototyped on the client for supporter games that are fully reviewed, I believe we recalculate those top 3 moves there since the top 3 moves are based off of a quick scan of the game not the fully reviewed data. But yeah once we get it dialed in to work the best it can work, I'll need to port that over to the server side to work for non supporter games.

If someone does this, keep in mind that score isn't available for Leela Zero reviewed games, only Kata Go games (although katago is the default and by far most used at this time)

**Comment by benjaminpjones** [comment]
Thanks for the additional info!
