### ISSUE TITLE
more dev help (questions and recommendations)

### ISSUE THREAD

**Issue by ClemensSahs** [online-go/online-go.com#1350]
Hallo,

I play a long time on your WebApp and I want to help you somewhere so I look to the source code.

### Currently I have some little and some big questions.

- I don't find test or I'm blind?
- What is your position to react Hooks, in my mind it makes component smaller and create a much better overview
- out of the topic of react-hooks, I recommend react "function component". "class component" don't capsules logic clearly enough and the testability are more complex.

### change or use some library

1. _[modal](https://www.npmjs.com/package/modal)_ last update in 5 years ago
[npm trends to modal libs](https://www.npmtrends.com/react-overlays-vs-react-modal-vs-popper.js-vs-react-popper-vs-modal)
- [react-modal](https://www.npmjs.com/package/react-modal) [bundlephobia from modal](https://bundlephobia.com/result?p=react-modal@3.12.1)
- [react-popper](https://www.npmjs.com/package/react-popper) [bundlephobia from react-popper](https://bundlephobia.com/result?p=react-popper@2.2.4)

2. pimp D3 with [visx](https://airbnb.io/visx/gallery) [bundlephobia for visx](https://bundlephobia.com/result?p=@visx/visx@1.3.0)
is great canvas library and use under the hood D3
Biggest pro it have many small sub libs so we can use only a subset and can save transfer less data

best regards

Clemens

**Comment by anoek** [comment]
Re tests: There are not that many yet but you'll see some by benjaminpjones for the translation stuff. Tests are great when they can test things that are wont to break and protect us from ourselves. Tests are not good when they get in the way. So I welcome them, but we don't want to test just for testing sake, we want them to be genuinely useful.

React hooks are good, we use them in a few places. Most of the code base was developed before hooks, which is why you won't see them in more places. There are still a few things that components do better, but for the most part I generally prefer hooks I think.

I'm open to changes in what libraries we use, all I ask is you be wary of bloating the bundle or causing performance issues on lower powered devices.

**Comment by benjaminpjones** [comment]
Let me know if I can answer any questions about existing tests.  They are the files suffixed with .test.ts.  The testing framework is [Jest](https://jestjs.io).
