### ISSUE TITLE
Automatch blitz with Fischer time counted as a live game

### ISSUE THREAD

**Issue by TeXitoi** [online-go/online-go.com#1378]
**Describe the bug**

I've selected Fischer time in the preferences of the blitz game. I've done such a game, and it appears as a live game in the history and rank calculation. See for example https://online-go.com/game/30655665

**To Reproduce**

1. Go to 'play'
2. Click on 'settings' of 'Quick match finder'
3. Blitz Time control "prefer Fischer"
4. close preferences
5. blitz automatch
6. The time limit will be "Fischer: Clock starts with 30 seconds and increments by 10 seconds per move up to a maximum of 1 minute."
7. Play the game
8. Look at the game in your game history, it is "live" and not "blitz".

**Expected behavior**
When playing a blitz game with automatch, the game is counted as blitz.

**Comment by shinuito** [comment]
It would be nice if these issues were fixed.

When the rating system changed in January it reclassified all games, so many games that were blitz got bundled into the live ratings instead, which I think was probably a bad idea for anyone who cares about these individual ratings instead of the overall.

Anyway aside from that I believe that 

https://github.com/online-go/online-go.com/blob/8a8d763db1ecc71465d31ac69eac2836932c4a00/src/components/TimeControl/util.ts#L168

and 

https://github.com/online-go/goban/blob/3897a698b130c9c6c21f1c01eb5ae0238728ffe2/src/GoUtil.ts#L217

are the lines where these thresholds are defined.

I've made some test unranked games and I think the calculations are pretty poor the way they are now for classifying Blitz games and I've logged some examples in the forums thread.

https://forums.online-go.com/t/blitz-game-problem/38453/16?u=shinuito

Basically from what I can see, there's an arbitrary `90` in the formulae, for calculating the time per move. Maybe this was some simplification to make time settings consistent across board sizes? At least it was mentioned that this number used to be different for different board sizes.

Anyway the `90` is arbitrary, but the more important issue I believe is how one can get very silly games classified as "Live" and "Blitz".

For example the current automatch settings for "Blitz" use 10s byo-yomi and since there's a strict <10s in the code, none of these games, the automatch or the sitewide "Blitz" tournaments count as Blitz.

Furthermore one can have silly things like 5m+1x6s byo-yomi and 0s+100x9s counted as Blitz but 0+1x10s counted as live, since the code doesn't take into account the number of byo-yomi periods.

I haven't thought about or tested the Canadian byo-yomi one, but if I have more time I'll think about it.

Realistically I would've thought the calculation should resemble something like `max_time_possible/X`, which if one imagines a player could spend all their main time on one move then:

for byo-yomi, `max_time_possible=main_time+N*T +(X-1)*T` , where the settings are `main_time+N x T` seconds, and `T` is the byo-yomi increment and X=number of game moves. This would be similar to the formula in the code in that it would simplify to `(main_time+(N-1)*T)/X+T` except one sees that the main time should be adjusted by (N-1) times the increment. Then one chooses X instead to be some reasonable value for a typical number of moves in a game (90 is reasonable?).

For Fischer I think the calculation in the the code already is fine, since one could use all main time on one move and "live off the increment after" so that the average time per move is `(main_time+(X-1)*T)/X≈main_time/X+T`.
