### ISSUE TITLE
Humble rank is broken.

### ISSUE THREAD

**Issue by koshogs** [online-go/online-go.com#1400]
**Describe the bug**
A completely new account is able to accept games limited to 6k or stronger.

**To Reproduce**
1. With one account create a custom game with 6k minimum rank restriction.
2. With a second, completely unranked account, accept the game on the play page.

**Expected behavior**
The high uncertainty in a new account is supposed to mean that their ability to accept and post games is governed by their 'humble rank' AFAIK

**Examples**
Both of these games were created with a 6k minimum and accepted by a completely unranked account: 
1. https://online-go.com/game/31053332
2. https://beta.online-go.com/game/10056

**Desktop (please complete the following information):**
 - PC Windows 10
 - Browser: Chrome, Opera and Edge

**Additional context**
I now regret cancelling the game because the user went on to have a string of cancellations as their first experience of OGS. If a new user is unfamiliar with kyu/dan ranking then they may even be targeting the sdk games on the play page over the ddk ones that would suit them better. Unfortunately other sdk players may bail on such games only after playing a few moves which can 'trap' the new user in a false sdk rank. eg: 

"In the OPs case, his first couple of games were experienced players who bailed on him ( :frowning: ) causing him to win, and the rating shoot up wrongly. This has been fixed." Quoted from: https://forums.online-go.com/t/rankings-explanation/34160/13

**Comment by BHydden** [comment]
@anoek  this is ongoing and came up again most recently [in this forum thread](https://forums.online-go.com/t/new-here-how-do-i-get-a-ranking/24531?u=bhydden).

**Comment by shinuito** [comment]
Bumping this https://forums.online-go.com/t/all-new-players-should-be-ranked-via-bot/40874/66?u=shinuito

In summary some players believe it’s not beginner friendly to have new players needing to lose several games (possibly 6 or 7 if there’s nothing unusual) in order to reach 25kyu or thereabouts, which is reasonable.

In theory with the humble rank stuff the new players rated 1500±350 (~6kyu) but treated as 1150 (11.9~12kyu) which is how it is currently displayed in the profile, would likely be able to challenge 20kyu players initially.

**Comment by shinuito** [comment]
Alternative suggestions in the thread include 

- forcing players to get a ranking from bots (OP but rejected mostly)
- Allowing players to set an initial rating at 25kyu or some other starting point
- possibly enabling rank reset requests, if there’s some issues with being able to set your own initial rating.
- Dropping the rank restriction for challenges generally, since in tournaments and ladders it seems one can play ranked games with players that are more than 9 ranks apart.
- Some kind of shadow rank (which I believe is like picking your own rank for matchmaking while a new player [?] ranked, but not actually setting the real rank), so similar to humble rank in way.

My comments are in the thread, so I won’t comment on any suggestions here.

**Comment by GreenAsJade** [comment]
Humble rank is no longer active - it was removed in the "New User Stream Selection" update.
