### ISSUE TITLE
[FEATURE] : Option to Delete Account

### ISSUE THREAD

**Issue by 641i130** [online-go/online-go.com#1428]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that we are not able to delete our account (I can't find a delete option anywhere; If I missed it, it should be more obvious!).

**Describe the solution you'd like**
We should have the option to delete our account! It's as simple as that.

**Comment by BHydden** [comment]
Your games are not your own but co-owned by your opponent, for this reason moderators (or you) can annonymise your personal details (username, email, etc.)

**Comment by benjaminpjones** [comment]
I don't know if games stand in the way of allowing account deletion.  The games can still exist, but the player id for the deleted player could be set to undefined.

**Comment by 641i130** [comment]
Then along with account deletion, why not just delete all the games the user is currently in? I made my account on a different address by accident and would like to get it deleted. Is this too much to ask for?

**Comment by GreenAsJade** [comment]
Yes, it is too much to ask for.    The gams you previously played, and the games you are currently, in, are both shared by you and your opponent.  

"The games can still exist, but the player id for the deleted player could be set to undefined."

This is what happens when people request account deletion - the player ID is is set to a random value, disassociating them from it.

Getting this done is as simple as asking.

**Comment by benjaminpjones** [comment]
>"The games can still exist, but the player id for the deleted player could be set to undefined."
>
>This is close to what happens when people request account deletion - the player ID (name) is is set to a random value, disassociating them from it.

Close, but I can think of one key difference.  Simply anonymizing the username still leaves the profile intact, so it is relatively easy to deduce a player's old name if they have ever used game chat.  Here is an example:

https://online-go.com/player/850082/

I can tell you a couple things about this account that I wouldn't have been able to if it had been more thoroughly deleted:

 - Their name was KataGo-mini
 - They are a member of the KG/LZ/Leela group
 - They played 50 ranked games over the course of about a month

I know this info isn't that interesting, but my point is it's almost like the account wasn't anonymized at all.  I was able to find more accounts like this, but I only felt it was okay to share this one since it is a bot.  For others, I was able to deduce full names.

>Getting this done is as simple as asking.

Simple enough for you and me, but I imagine most people who want to delete their accounts are not familiar with the communication channels that exist on OGS.  As you can see, this question pops up here on GitHub, [on the forums](https://forums.online-go.com/search?q=delete%20account), and I believe people sometimes reach out to contact@online-go.com for this.  I can only imagine the cases where people have tried to find the delete button and just gave up because they didn't know who to contact.  Is there any reason why we don't just provide a password-protected button in account settings that does whatever the mods would do automatically?  This has the following benefits:

- Ease of discovery
- More thorough account deletion (e.g. delete or hide the user profile)
- Slightly less mod work, and more consistent account deletion

----

All this to say, I don't really understand why the official answer is invariably "Games belong to two people, therefore we can't allow account deletion."  Some sort of automated account deletion is offered in user settings on most websites that have log-ins, including our popular chess analogs.  Why not keep this feature on the roadmap?

**Comment by benjaminpjones** [comment]
Fixed by 631c3b4?
