### ISSUE TITLE
"Computer" button on Play page missing settings

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#1443]
**Describe the bug**
When you click the `Computer` button on the [Play page](https://online-go.com/play), it is missing the options `Game Name` and `Rules` that are otherwise present if you direct challenge or rematch against an AI

**To Reproduce**
1. Go to [Play page](https://online-go.com/play)
2. Click on 'Computer`
3. See that options for `Game Name` and `Rules` are missing.

**Expected behavior**
All the options that are available with a standard challenge should also be available on the [Play page](https://online-go.com/play).

**Screenshots**
![image](https://user-images.githubusercontent.com/28991649/113670106-07b09180-96f8-11eb-857c-a3c0a696f9e5.png)
![image](https://user-images.githubusercontent.com/28991649/113671103-4430bd00-96f9-11eb-952d-dff2f153eb0f.png)
![image](https://user-images.githubusercontent.com/28991649/113670742-d71d2780-96f8-11eb-9b10-f7a98e256511.png)

**Comment by benjaminpjones** [comment]
Is this not by design?

https://github.com/online-go/online-go.com/blob/a6a01efc6aad1a44e378b6a13bce2593c1a63e87/src/components/ChallengeModal/ChallengeModal.tsx#L642-L651

**Comment by anoek** [comment]
Game name was left out in favor of having that space used by the AI dropdown, and I didn't feel naming those games was all that important (maybe I'm wrong there? Not sure, but I haven't heard any complaints before).

Rules is left out because most AI's can only play Chinese rules, so that's enforced.

**Comment by BHydden** [comment]
I forgot to include a detail, apologies.

The inability to set a game name has the effect of it being locked to the chosen name of your last custom game.

![Screenshot_20210406-213341_Brave.jpg](https://user-images.githubusercontent.com/28991649/113704792-f67b7b00-971f-11eb-9381-4d04b3e59b84.jpg)

**Comment by anoek** [comment]
Ah, yeah that should be blanked

**Comment by koshogs** [comment]
"Not sure, but I haven't heard any complaints before." Sorry but I'm complaining. 

I'm told bots are not supposed to accept other people's custom games but I was tricked by the details page into thinking that's what a bot was doing. The creator is shown as the human player and the title was the same as for a custom game. Some indication in 'details' of how the game was created would be good in that regard.

**Comment by benjaminpjones** [comment]
## Good First Issue

The game name should be set automatically, instead of using previous settings.

### Code Points

- [`ChallengeModal.createChallenge`](https://github.com/online-go/online-go.com/blob/a6a01efc6aad1a44e378b6a13bce2593c1a63e87/src/components/ChallengeModal/ChallengeModal.tsx#L405-L417): Here, special settings for computer matches can be set (`this.props.mode === "computer"`).  In this case the name of the game (`challenge.game.name`) is the relevant setting to update.

### Additional info

If you want to use the username of the bot in the game name, it is possible to get that information from `bots_list`. Unfortunately, the types aren't totally documented, but here is an example of `bot.username`: [`ChallengeModal.basicSettings`](https://github.com/online-go/online-go.com/blob/b48ed9f42268c2f8e8f691157cdb1842e86599e3/src/components/ChallengeModal/ChallengeModal.tsx#L633)

**Comment by maurelio1234** [comment]
Hi!

I'd like to take this one, so the idea is just setting the `game.name` with the name username of the bot?
What about something like `X vs Y` like I see some games are automatically named ?
Or a standard name like `Computer challenge` (like `Friendly match` and `Ladder Challenge`)?

**Comment by maurelio1234** [comment]
Hello,

there goes a first proposal for discussion... to keep it simple I use `Friendly Match` as the default game name (just like when the user didn't set another game name) for computer games too... 

I don't see as these games are less 'friendly' as human ones ;)
