### ISSUE TITLE
Access to privacy controls unclear

### ISSUE THREAD

**Issue by benjaminpjones** [online-go/online-go.com#1467]
**Describe the bug**
If you are in a private game, but not the game creator, you will have access to the privacy controls, but will not be able to edit them.  This is fine, but the interface appears to allow editing, up until the server sends back a "Permission Denied" error.

**To Reproduce**
1. As Player 1, create a private game and challenge Player 2
2. As Player 2, accept the challenge
3. As Player 2, open "Access settings"
4. Try to add/remove a user from the settings.
5. Receive "Permission Denied" error

**Expected behavior**
1) Player 2 can edit the access settings.
2) The access dialog changes to reflect read-only access for read-only users.

**Screenshots**
<img width="600" alt="Screen Shot 2021-04-25 at 2 47 23 PM" src="https://user-images.githubusercontent.com/25233703/116005518-53f34100-a5d5-11eb-96fd-025243365152.png">

**Comment by benjaminpjones** [comment]
Also, there should never be an [x] next to either of the players, because they cannot be removed.

**Comment by AlastairM-E** [comment]
Hi @benjaminpjones,

I am happy to take on this issue unless someone else wants to.

To confirm, the changes you want are:
* Player 2 to be able to allow users to access the game (by adding the them via the input field).
* Player 2 to be able to remove users from accessing the game (by clicking the [x] button up top their username).
* Any third-party user who is invited in, to be unable to add or remove users from accessing the game.

In addition, I had trouble understanding how the access controls work:
* I have looked in [this page in the wiki](https://github.com/online-go/online-go.com/wiki/The-game-view-and-playing-games#additional-game-actions), and I could not find anything on it.
* When trying for myself with 3 users (the 2 users playing the game & the watcher user - given access to the game by the access controls), I did not receive any information about the game as the watcher user, nor could I suddenly see the private game in the game navigation link.

[Here is a video of me](https://www.youtube.com/watch?v=hlZd1jZwMTA&t=152s) trying out the access controls (the first part is me going through the issue).

I need know how the controls works, so that if I create a fix I can test it properly and know I have not broken anything.

Finally, for handling read-only third party users (presumably the one added by the access controls):
* Do they get an access dialog control like the one below (with the usernames aligned)?
* Should the access controls even be available to them?
* Another solution?
<img width="960" alt="OGS--2021 10 13--third_party_access_controls" src="https://user-images.githubusercontent.com/47124313/137213906-73b2da16-e46a-4047-984a-583012a06002.png">

**Comment by benjaminpjones** [comment]
Hi @AlastairM-E, thanks for offering to take a stab at this!

> To confirm, the changes you want are:
> 
> - Player 2 to be able to allow users to access the game (by adding the them via the input field).
> - Player 2 to be able to remove users from accessing the game (by clicking the [x] button up top their username).
> - Any third-party user who is invited in, to be unable to add or remove users from accessing the game.

Yes, in my ideal world, _Player 2_ would be able to make the same changes to the Access Settings as _Player 1_.  My concern is the fix needs to occur in the backend.  Perhaps @anoek can help with that?

Another "solution" that only involves only frontend changes would be to make it more clear that _Player 2_ only has read-only access. (Disable/Hide "Grant Access" controls, as shown in your screenshot)

> Finally, for handling read-only third party users (presumably the one added by the access controls):
> 
> - Do they get an access dialog control like the one below (with the usernames aligned)?
> - Should the access controls even be available to them?
> - Another solution?

Heh I hadn't even thought about that.

Either would probably be fine, but I think it makes sense to allow the _watcher_ to view the access settings (but read-only like your screenshot).  It also gives them a quick way to see that the game is private.

**Comment by anoek** [comment]
Yeah you'll need me to update the server so either player can perform the update query. I'll add that to the todo list, should be a quick fix, I'll try and get it out this weekend or monday.

**Comment by anoek** [comment]
This has been updated to behave as I think is more desired, both players (or the game creator if that is different) can now grant and remove access.
