### ISSUE TITLE
CPU usage high just sorting chat lists for windows I'm not looking at

### ISSUE THREAD

**Issue by rileylark** [online-go/online-go.com#1476]
**Describe the bug**
When someone else joins or parts a chat channel, the entire member list is sorted twice. For me, mid-day in the USA, this takes on average about 35ms of CPU.

![image](https://user-images.githubusercontent.com/1630424/117707416-2fca5f00-b194-11eb-8c69-3e827dc75d56.png)

It's happening at a rate of something on the order of 20Hz

![image](https://user-images.githubusercontent.com/1630424/117707553-4ffa1e00-b194-11eb-966e-26de4cf178f9.png)

On my MBP this means about **25% CPU usage** for this tab - even though I'm not even looking at the chat screen. On my phone, this means my battery is draining really fast when I'm just contemplating a static Go board for minutes.

**To Reproduce**
1. Join these chat channels
![image](https://user-images.githubusercontent.com/1630424/117707710-7d46cc00-b194-11eb-9651-28c98dcd9926.png)

2. Wait for mid-day USA
3. Go to a static game, not a chat room

**Expected behavior**
Low CPU usage 

**Actual behavior**
High CPU usage!

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Brave (Chrome)
 - Version 1.24.82 Chromium: 90.0.4430.93 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android
 - Browser: Brave

**Comment by anoek** [comment]
Yep any/all of those would be awesome. Thanks for hunting that down, you'll make a lot of people happy if you can make that go away :)

If you're seeing chat sorting happening when you're not on the chat screen, I suspect there might be something going on stemming from the use of the `ChatIndicator` system. That system doesn't need any sorting at all I don't think, nor an active list of the users even, but I think those things probably just happen because it's re-using a lot of state and code from the chat system that drives the chat page, which does need those things.

**Comment by rileylark** [comment]
Great, I might check it out this week!

**Comment by rileylark** [comment]
So I can see the big lists to sort, it might be nice to develop this against production APIs - will it work to just swap in production values to the dev environment?

**Comment by rileylark** [comment]
I made progress on this - switching to an insert/remove instead of re-sorting each time saves a buncha CPU. Will post PR later today

**Comment by rileylark** [comment]
I think this is resolved - at least down to "it's not the biggest CPU issue anymore." Ok for me to close it? Let me know if you'd rather keep it open!
