### ISSUE TITLE
No mail notifications when it is my turn to move

### ISSUE THREAD

**Issue by tegais** [online-go/online-go.com#148]
### Summary

No mail notifications when it is my turn to move even though the correspondent item is checked in the settings. 

### Environment

 * Windows 10
 * Firefox
 * 51.0.1 (32-бит)

### Steps To Reproduce:

1. Start a correspondence game
2. Check the "It is my turn to move" item in Email Notifications settings
3. Wait until it is your turn to move and see that there is no email notification.

### Additional Information:

https://forums.online-go.com/t/no-more-email-notification-since-upgrade/10569

**Comment by anoek** [comment]
Do you happen to leave a browser window open connected to OGS? We don't send emails if we see that folks are online (aka have a browser window open).

**Comment by tegais** [comment]
No, I don't leave a browser window open.

**Comment by tegais** [comment]
I receive the notifications now. Thanks.

**Comment by arnaudgo** [comment]
Hello,

For the science:

I have never ever received any mail notifications since I joined OGS and I have never changed my settings (today all the checkboxes are checked).

I'm almost always on OGS night and day, almost... but when usually from mobile so I make breaks, sometimes... 

I haven't tried uncheck then check again. Should I do something like that ?

I wrote "for the science", because I don't miind receiving emails or not ... actually I prefer not receiving them but for debugging purposes, I may accept to activate them ... if possible :-)

Arnaud
