### ISSUE TITLE
Didn't detect dead stones, and when selecting didnt work and put accepted

### ISSUE THREAD

**Issue by BuddhaCodes** [online-go/online-go.com#1545]
I am not sure if it is a bug but the dead stones where not detected costing me the game but futhermore when using the dead stone selector it didnt work and instead put the game as accepted and with a quick reaction of my oponent cost me the game. 
This is the game.
https://online-go.com/game/38617450

**Comment by AlastairM-E** [comment]
Hi @BuddhaCodes,

### Confirm Issue

I want to check I have got the issue correct.
* Are you referring to the dead stones in the green circle as not being counted as dead (see image below)?
![image](https://user-images.githubusercontent.com/47124313/142730668-57d0f909-3e37-4bd6-b1d7-ee2ba4d6b7fc.png)

### My Analysis

From my counting (which is error prone), it seems like the computer counted correctly.

In terms of territory (&& separate between different territories):
* Black: 77 - [26 + 20 + 8 + 2 + 21] = [(26) 5 + 1 + 4 + 3 + 3 + 3 + 1 + 2 + 2 + 2 && 4 + 3 + 3 + 3 + 5 + 1 + 1 (20) && 1 + 2 + 1 + 2 + 1 + 1 (8) !! 1 + 1 (2) && 2 + 1 + 1 + (3 * 4) + 2 + 2 + 1 (21)].
* White: 64 - [6 + 49 + 9] = [2 + 3 + 1 (6) && 4 + 5 + 7 + 3 + 2 + 3 + 3 + (3 * 4) + 7 + 2 + 1 (49) && 2 + 2 + 2 + 2 + 1 (9)].

In terms of dead stones, it does seem they were accepted (capture readings from image below):
* White has 11 stones marked + 2 from previous captures + 1 point given with handcap. If you add the 5 points from the stones marked green by me above + 0.5 komi, that is 19.5 [11 + 2 + 1 + 5 + 0.5], which added to the territory 64 + 19.5 is equal 83.5.
* Black has 2 inside territory plus 8 from captures in game. Added to the 77 territory points makes 87 [77 + 10]. 
* That would lead to black winning of course.
![image](https://user-images.githubusercontent.com/47124313/142731157-049b40e4-ecc4-4037-8340-a79529062919.png)

If I have made a mistake or misunderstood the issue, please let me know, but if I am right, the dead stones were counted correctly and the game score is accurate.

**Comment by benjaminpjones** [comment]
I believe the issue is that @BuddhaCodes expected the territory on the right to be counted as white territory, which it wasn't.  That is a reasonable expectation, and is supported by the fact that the AI review shows white ahead by 20 pts.

<img width="942" alt="Screen Shot 2021-11-28 at 2 46 01 PM" src="https://user-images.githubusercontent.com/25233703/143783560-cfe3be97-4b19-4885-9508-2a6698a555fa.png">

However, I think this can be chalked up to user error since the boundary was not sealed (L6), and white did not verify the dead groups before accepting the result.  If there is a bug in the acceptance flow, then steps to reproduce would be good.  Otherwise, I suggest this issue be closed.
