### ISSUE TITLE
when logging in, a wrong password leads to oauth screen, not to a notification that password was incorrect

### ISSUE THREAD

**Issue by kylebakerio** [online-go/online-go.com#1546]
see title

in chrome

can provide further details if necessary

**Comment by anoek** [comment]
This is the expected behavior if the account was created with a social auth mechanism (ie login with google or facebook or whatever)

**Comment by kylebakerio** [comment]
I'm not sure, but I don't think I did, since I have a username and password. Also, it was super confusing, and wasn't until I checked my password manager that I realized I was using the wrong one. Seemed like just a website glitch.

**Comment by anoek** [comment]
Interesting, if you could send me your username, either here or via PM (anoek on the server), I'd like to look into it

**Comment by kylebakerio** [comment]
username is 'finetype'

**Comment by anoek** [comment]
It does look like there's an association with google auth in there, so you should also be able to login via google as well as login/password. The account is the same as is listed as your email address.

Ultimately, this is the expected behavior, as we want to help folks who can't remember if they set a password or clicked a social auth button, if they try a password but they logged in with google, we direct them there instead kind of thing.

**Comment by kylebakerio** [comment]
In my case, I was on a new laptop, and had not used that google account yet within Chrome. I also did not expect both to be possible--that seems pretty odd. I would suggest giving some kind of indication to the user about what is happening, I think less savvy users would have just created a new account and considered their old one lost in this case.

**Comment by anoek** [comment]
Indeed, better messaging if nothing else
