### ISSUE TITLE
Negative komi iOS support

### ISSUE THREAD

**Issue by icy31k** [online-go/online-go.com#1556]
Playing lots of handicap games lately. There's a problem with UI on any iOS device:

One cannot use the komi spinner to set up values to negative. There's neither spinner nor manual text edit available (validator wouldn't let ya). 

You really need a PC/Android platform to do that, except for Rematch button.

![IMG_20211128_084812](https://user-images.githubusercontent.com/2444687/143731774-881076e9-57a0-45b3-8a0d-d07e4d6f43bf.jpg)

**Comment by benjaminpjones** [comment]
Here's the relevant code point for anyone interested: [ChallengeModal.tsx > advancedSettings](https://github.com/online-go/online-go.com/blob/b48ed9f42268c2f8e8f691157cdb1842e86599e3/src/components/ChallengeModal/ChallengeModal.tsx#L906)

However, the fix is unclear to me since input/mobile keyboard interaction is so sticky, but perhaps here's a StackOverflow question that helps: [Best settings for HTML <input type="number">, for mobile devices](https://stackoverflow.com/questions/51660812/best-settings-for-html-input-type-number-for-mobile-devices). FWIW I have this issue on Samsung as well ([SO: input type=number not possible to insert negative numbers on mobile phone](https://stackoverflow.com/questions/21677695/input-type-number-not-possible-to-insert-negative-numbers-on-mobile-phone)).

**Comment by icy31k** [comment]
Probably the easiest way to deal with it, is adding "negative" checkbox, which would replace value, adding a minus sign to the field value.

That requires no component swap depending on platform, and keeps the current validation intact.

**Comment by shinuito** [comment]
I seem to be able to create negative Komi games on iOS in the safari browser at least.

![EE2C4438-F131-4351-9716-E9E2B3A8557B](https://user-images.githubusercontent.com/26803867/145918177-ea80fe40-a0be-49b1-b7bf-077c057479d0.jpeg)
![C40D6DE2-736C-4F23-92CC-A14F22B2F3FC](https://user-images.githubusercontent.com/26803867/145918183-3e2b59be-890a-44cb-8d07-628fa89a5af7.jpeg)

There is a box to edit the komi. If one deletes the komi, it will default to 0, at which point you’ll have to put the cursor/blue bar in front of the zero to input a minus sign. You could also type 010, you can then delete the first 0 and then put a minus sign in in front of the ten.

**Comment by icy31k** [comment]
For me, and few other guys, it doesn't allow typing the minus sign in that text field.
