### ISSUE TITLE
"Accept removed stones" button is disabled too frequently and the reason needs clarification to the user

### ISSUE THREAD

**Issue by imdj** [online-go/online-go.com#1583]
This scenario happens far too often for me: Both players pass, the result is fine, the button is there but in a blink you try to click accept only to find it got disabled for a blink sec then enabled and so on until I guess one of the parties manages to accept and it stabilize.

It's likely doing some checks on the backend but this kind of UI glitches is bad for the user experience and overall frustrating (unexpected behavior).

**Comment by anoek** [comment]
That's interesting, first i've heard of it blinking. There's an intentional few second delay to prevent someone from accidentally accepting the board stat if it changed right before clicking the button, but it shouldn't blink persay.

Are you seeing this on a mobile or desktop device? What version is your device? Which browser are you using?

**Comment by imdj** [comment]
By further testing, yeah it's not blinking randomly but it gets disabled and enabled whenever there's a re-calculation even if someone is just clicking auto-score over and over again without changing anything really.

Maybe some players press auto-score multiple times just to make sure.

Would you like me to close the issue or consider it a UX enhancement for the future (There must be a better way to handle this)?

**Comment by anoek** [comment]
That is troubling that you experience that a lot. Anything come to mind for a better experience?

I'd say if we can come up with a better system, we should describe it here and keep the issue open, otherwise we should close it.

**Comment by imdj** [comment]
No solutions off the hat.
But glad that I understood the behavior better.

**Comment by BHydden** [comment]
Sorry @anoek it seems we failed to make you aware of this earlier, either in [this forum thread](https://forums.online-go.com/t/why-seven-clicks-to-end-game/40087/33?u=bhydden) or by creating a ticket here... whoops.

**Comment by BHydden** [comment]
IIRC it was agreed in the above forum thread that the intended function was to prevent accepting immediately after a *change* but instead it prevents accepting after a recalculation, even if nothing is change. Also, even if one has already accepted the blinking continues which adds confusion. 

I propose:

Accept button should be clickable unless,
1. life and death status of at least one stone was recently changed, or
2. player has already accepted the current board state.

**Comment by anoek** [comment]
Well it needs to be clickable again after it's been accepted in the even that it was changed, but agreed it certainly doesn't need to blink if nothing has changed, that's likely an artifact of me just blasting out an autoscore update or something. That autoscore button should be limited too if it's causing problems. 

We might also benefit from having some text show up while it's disabled, letting folks know that your opponent is making changes to the score, or something to that effect.

**Comment by imdj** [comment]
I'll try to explore alternative workflows where user is aware of the change like using stronger visual indicators for a start to see if we can hopefully eliminate the need to disable the button and ultimately make the user flow more natural.

**Comment by imdj** [comment]
Here's what I have in mind for now:
Similar to the current workflow except each player has their own "draft board" that they can use to propose a score and if both proposals match the score is settled. (See image attached)

Players can view each other proposals and discuss it in the chat just like variations.

Would like to hear your thoughts on this @anoek @BHydden .

![diagram](https://user-images.githubusercontent.com/69906094/147534993-4d61bff1-f63a-452e-93b4-1d5918a1015f.png)

**Comment by imdj** [comment]
Why I propose going in this direction instead of adding an explanation to why it's being disabled:

I feel that simply adding more clarification and such is really treating symptoms (user confusion) while the underlying original issue (attempts to manipulate score and accidentally pressing accept) that lead to disabling the button in the first place would still be buried.

**Comment by BHydden** [comment]
I really like this idea! Certainly shows promise :) anoek may need to verify whether such a path would generate too much server load but assuming it doesn't I think this is a really great idea :)

**Comment by BHydden** [comment]
I especially like the idea that one play can just leave the correct score accepted and the flailings of the other player do not affect that at all <3

**Comment by anoek** [comment]
> anoek may need to verify whether such a path would generate too much server load but assuming it doesn't I think this is a really great idea :)

No more than currently exists, I think this could be entirely a front end change and use the current back end plumbing, we already differentiate and send what each player has accepted, would be a matter of making use of that to do the preview boards, and then making changes to the flow of when the main board is updated and whatnot. 

> I especially like the idea that one player can just leave the correct score accepted and the flailings of the other player do not affect that at all <3

I like that too.

---

I feel like *in general* the current collaborative system works pretty good, but is obviously subject to abuse (intentional or otherwise), so having a natural switchover to "Ok now you're in complete control over what's going on on the board" sounds good to me.

A couple of use cases where I think the collaborative version does more good than harm:

  * new players don't always know what to do in this step, seeing the board change and the stones removed I suspect helps them kinda figure it out a bit during this phase
  * After the second pass in a correspondence game, often the player finishing will take care of scoring and submit their version, this just leaves the opponent to pop in and click accept the vast majority of the time which is nice, we still want that smooth flow I think (as opposed to having them pop in a game, click a button to load what their opponent did or have to rescore things themselves)
  * I imagine some people are lazy or take a break right after a game and let their opponent score, no need for both players to score most of the time after all - supporting that is a nice feature I think.


So in general I'm in support of a system that naturally switches over between a synchronized view of what's going on, and an unsynchronized view where you are in complete control.

What comes to mind initially is something like this:

* Initially the state is synced like we currently do
* When you make a change, you stop showing synchronized updates from the other player (but you still send yours so they can sync to you)
* If you click on their mini board, you discard your current changes and load the synchronized data and begin the synchronizing display again.
* If you click on your mini board, you load your accepted changes (if any) and stop synchronizing.
* If you're showing a synchronized display, disable the accept button shortly after a change like we currently do
* If you're showing your non synchronized display, no button disabling


Thoughts?

**Comment by imdj** [comment]
> - new players don't always know what to do in this step, seeing the board change and the stones removed I suspect helps them kinda figure it out a bit during this phase

This one is interesting. I guess for players who know Go but new to the site, a simple notes or walk-through for the first 5 games is sufficient. While those just starting out the proposal actually protect them and they should go with autoscore.

> - After the second pass in a correspondence game, often the player finishing will take care of scoring and submit their version, this just leaves the opponent to pop in and click accept the vast majority of the time which is nice, we still want that smooth flow I think (as opposed to having them pop in a game, click a button to load what their opponent did or have to rescore things themselves)

So, I guess the price is an additional click. I'm not aware of the statistics but if auto-scoring is accurate in most games then no need to even switch boards.

> - I imagine some people are lazy or take a break right after a game and let their opponent score, no need for both players to score most of the time after all - supporting that is a nice feature I think.

In this case nothing need to change here, ` accept removed stones = propose score ` -> and those the score is determined as usual when time runs out.



At first glance, I feel combining a synchronized and unsynchronized view would require greater attention from the user to keep track and likely hurt the code base at the same time.
The proposal really just de-coupled counting the score, everything else can remain the same. 

Anyway, since this change isn't urgent maybe we could leave it for a future re-design.

**Comment by BHydden** [comment]
> maybe we could leave it for a future re-design

/ checks notes

ok, I'll check back in in 3 years :sweat_smile:

**Comment by pdg137** [comment]
By the way, my impression is that the original issue (accept score button blinks off when there is no change) happens most often because of the opponent accepting the score.  Clicking "accept" disables the other player's button even if the first player had already accepted it!  So this happens at least once in every single game.

**Comment by BHydden** [comment]
> I'll check back in in 3 years

Better make that 2 😅

**Comment by BHydden** [comment]
I know some work has been done in this area in the last 2 years, but not sure it this specific issue was resolved or not...

**Comment by pdg137** [comment]
I think it still blinks when they accept the score, without reason or explanation.

**Comment by pdg137** [comment]
Actually, I've played a few more games since then and think that it's no longer disabling the accept button when your opponent accepts. So I think the main issue is fixed!

**Comment by anoek** [comment]
Thanks for letting us know!
