### ISSUE TITLE
29k players shown as 25.0k on the profile

### ISSUE THREAD

**Issue by pdg137** [online-go/online-go.com#1606]
**Describe the bug**

Ranks > 25k are used in most places but not shown on the player profile.

**To Reproduce**
1. Find a player with a rank greater than 25k (e.g. 29k).
2. Go to player page, e.g. : https://online-go.com/player/628419/Veraces
3. Observe that the rank says 25k and player card says 25.0k.
4. Observe that their rank in the recent game history below is well above 25k.
5. Try the ranking formula `30 - ln(rating / 525) * 23.15` to verify that indeed their rank is not 25k.

Additional confirmation that their actual rank is above 25k:

* You can't invite them to "25 kyu and above" tournaments (#1403)
* The actual rank affects matchmaking (#1336)

**Expected behavior**
The actual rank should be displayed on the player page.

**Screenshots**
![image](https://user-images.githubusercontent.com/466760/148577541-9d4d80da-1091-44c7-a597-177ce2c2b5f5.png)
![image](https://user-images.githubusercontent.com/466760/148578570-d1df70ca-b3f3-4dae-82d7-0dbe3d55b1ed.png)

**Comment by BHydden** [comment]
This is a feature, not a bug. Rating remains true so that real progress can still be tracked and matchmaking can be as fair as possible, but ranks are limited at 25k because according to anoek's experiments the impact of handicap stones stop having a meaningful effect on the result of the game below that skill level.

**Comment by benjaminpjones** [comment]
Is there a reason it isn't shown the same in every place? I don't understand why we'd show the uncapped rank in the game history, but cap it to 25k everywhere else...

**Comment by BHydden** [comment]
Again, for the purposes of tracking progress... it is nice to look back at your game history and see your rank climb from 32k to 29, even if it still says 25k at the top

**Comment by BHydden** [comment]
Just a few little gestures to help ease the burden of being "stuck" in 25k even when in reality they have gained several ranks worth of strength over that time.

**Comment by benjaminpjones** [comment]
Oops sorry for making you repeat yourself sometimes I just don't see things.

I wonder if there's a possibility to uncap the top number too if the only place where the cap is used is autohandicap.  I agree with pdg that the inconsistency is confusing (although I don't spend enough time looking at 25k accounts to notice :P)

**Comment by BHydden** [comment]
It's not just in handicap stones, it's in all match-making due to our 9 rank cap for rated games. It is true that the system will look at rating points to do match-making as fairly as possible, but if we hide the 25k cap too much or even just abolish it, then 32k players will find they can only play 23k or weaker which is a much smaller pool than 25k-16k and we don't want to find ourselves in the situation where some ranks are so accurate the user can't get a game...

Of course, you could then ask the question "why don't we just abolish the 9 rank limit for non-handicap games" which is an excellent question but now we're trying to discuss 3 very different things at the same time and coming to common ground on which path/s are best becomes tricky :)

**Comment by benjaminpjones** [comment]
I guess what I'm saying is: what's wrong with a profile/summary card showing someone's true rank?

Automatch and autohandi can still do special handling on the high kyus, but real rank shown everywhere in the UI

**Comment by pdg137** [comment]
> It's not just in handicap stones, it's in all match-making due to our 9 rank cap for rated games.

Oh! So 25k is supposed to be used everywhere *except* in the game history?

> It is true that the system will look at rating points to do match-making as fairly as possible

I don't understand this...so the actual unbounded rating *is* used in matchmaking? Is matchmaking for > 25k players actually explained somewhere? It's kind of hard to test without embarking on some serious sandbagging.

It does at least seem like the the player I linked to was able to play ranked games against players more than 9 levels above their "true" rank:

![image](https://user-images.githubusercontent.com/466760/148655410-7bb2df86-9b47-4542-87db-914280c0dbbc.png)

But issue #1403 makes me think that the true rating is still being used in some places.

**Comment by BHydden** [comment]
> Oh! So 25k is supposed to be used everywhere _except_ in the game history?

Correct, 25k should be the cap everywhere on the site except game history AFAIK

> I don't understand this...so the actual unbounded rating is used in matchmaking?

It's a little difficult to explain because we have both ratings and ranks.
Ratings are used by glicko, and as far as it is concerned anyone can play anyone. They're also used for pairing players with automatch, so if 4 players click automatch at the same time and they're all 25k, my understanding is the two weaker 25k will play each other and the two stronger 25k will play each other (I believe)

Ranks are what we squished on top, for historical aethetics and also for the handicap system. We mapped certain ratings to certain ranks, and capped ranked games to ±9 ranks and capped total available ranks to 25k lower-bound and 9d (or 9d+) to upper-bound.

I hope I explained that well?

**Comment by pdg137** [comment]
Yeah.  Seems like if it's used for some mostly invisible tiebreakers that's not a big deal; the chance of 4 simultaneous clicks should be zero anyway.  But as long as we're displaying both versions of the rank if different places shouldn't there be some kind of unifying explanation visible somewhere? What if the player card showed the two explicitly:

![image](https://user-images.githubusercontent.com/466760/148666018-dd8f1abb-bba6-452b-8237-3029eeb2ca08.png)

The deviation seems especially meaningless when applied to the capped rank.

**Comment by BHydden** [comment]
well the rating is always correct even if the rank is capped, so just go off that?

**Comment by pdg137** [comment]
Well, I'm closing because it sounds like my initial statement about ranks > 25k being used in most places is wrong. I do think capped players should get some kind of explanation though.
