### ISSUE TITLE
With handicap, two passes does not always end the game

### ISSUE THREAD

**Issue by pdg137** [online-go/online-go.com#1612]
**Describe the bug**
In some handicap games, two passes (or actually any number of passes) is not sufficient to end the game. It seems that a few actual moves need to be played first.

**To Reproduce**
1. Start a 9-handicap Japanese rules game.
2. Have White pass.
3. Have Black pass.
4. See that it's now White's turn again.

**Expected behavior**
The game should end after two passes. Or if this is intentional, there should be some kind of error message like "you must play at least X moves, please continue."

**Screenshots**
![image](https://user-images.githubusercontent.com/466760/148690671-b528f454-e92d-4672-bda3-53cb7e2e43fb.png)

**Comment by anoek** [comment]
I think technically it'll work after you've passed hc+1 times. This is likely because we didn't check if the current rules use fixed placement or not, we only check against handicap count (since for free placement of handicap games, we want to support someone passing on all of their handicap stones, which is valid.

I'm closing as wontfix because changing that code, while probably pretty easy, should involve a lot of testing to make sure I didn't inadvertently break anything, and I don't think going through that much effort is worth it for this spiritually invalid edge case.
