### ISSUE TITLE
Accepted game no longer switches focus to window

### ISSUE THREAD

**Issue by danielb2** [online-go/online-go.com#162]
### Summary

 OGS used to make the browser window active when the game started after I initiated a challenge. What happens now is that I setup a new game, and it takes a long time to get a match, and then I'm doing other things in the meantime, and I timeout or the challenger gets fed up and cancels ... watever the outcome, it was better before

### Environment

 * Operating system:  macOs
 * Browser:  Chrome
 * Browser Version: 56.0.2924.87

### Steps To Reproduce:

1. create a new game
2. browse another window or another app

### Expected result

The browser window should become active when the game is accepted and OS should switch to the app and proper window

### actual result

At most there's a notification which can sometimes be overlooked if busy

**Comment by anoek** [comment]
This used to happen because we were using `alert()` to notify users. In general, `alert()` was pretty well hated so we switched to sweetalert for fancy dom based alerts, however the side effect is that it doesn't grab focus quite as much as alert.

I always liked the fact that we would do a "your game has begun" alert that would focus the window too. Maybe can add a setting that people can turn on that would then emit an alert when games start (bonus points for only emiting the alert if the window isn't already in focus :) ).

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
