### ISSUE TITLE
Voice option for Brazilian Portuguese

### ISSUE THREAD

**Issue by bani** [online-go/online-go.com#1741]
I'd like to propose the inclusion of Brazilian Portuguese as one of the voices available, since Brazil has a large Go community and it could also be used by other Portuguese speaking countries.

I can volunteer to record the numbers and phrases myself and write the data for the sfx_sprites file, although I'm not a voice professional and I don't have access to a completely noise free environment. I've recorded the numbers file as an example of what I could provide, and if you think the quality is acceptable I can record the other file. It's available at https://github.com/bani/online-go.com/blob/voice_pt_br/assets/sound/pt-br-bani-numbers.v6.webm

**Comment by anoek** [comment]
Hi @bani! 

Sorry for the delayed response, and thanks for being willing to do this!

I found the script and the audio processing stuff I used when doing this initially, so this should be reasonably straight forward.  Below is the English script, it seems like you are quite fluent in both languages so I presume it'll be no problem to translate it appropriately. What we need is for you to make a recording of the translation, including a short pause between each number spoken and each phrase. The delay was a bit too short in the audio sample you provided, just give it a little more time between each number / phrase. Record the numbers as one audio file including all numbers 0 through 60, and then all the phrases as one big audio file. I then have a software routine that goes through and cleans up the audio, splits it up on those silent spaces you give between each phrase, normalizes the volumes, recombines the audio file and creates those sprite sheets automatically.

Here's the script in English, when you translate it keep the order of everything the same that way the software to label everything just kinda works, and if you can, upload the original uncompressed audio .wav file, preferably recorded at 44.1khz or 48khz (higher is fine too, though it probably won't make a difference in the end result). Other uncompressed formats are fine too, .flac or whatever, we just want to avoid the compression artifacts initially since we'll be passing it through several audio processing phases to cleanup and normalize it before repackaging it.

Thanks again for being willing to do this! Here's the script:

```
Begin

Game started

Game over

Main time

Black wins

White wins

You have won

You have lost

Tie

Draw

Stone removal

Remove the dead stones

Game paused

Game resumed

Undo requested

Undo granted

Your move

Disconnected

Reconnected

Your opponent has disconnected

Your opponent has reconnected

Your partner has disconnected

Your partner has reconnected

Player disconnected

Player reconnected

Time

Timeout

Byoyomi

Entering byoyomi

Last Byoyomi

Overtime

Entering overtime

Period

5 periods left

4 periods left

3 periods left

2 periods left

1 period left

Last period

Match found

Game found

Game accepted

Challenge accepted

Challenge received

Review started

Pass

Your opponent has passed

Confirm the score

Tournament starting
```

**Comment by bani** [comment]
@anoek sounds good. So for the numbers I record them in normal numeric ascending order, and it's your script that sorts them in "string" order?
I'll try to record when there is a minimal amount of noise here since you want the raw file. I had used a RNN filter to remove some of the noise in the version I shared previously.

**Comment by anoek** [comment]
Yep normal numeric ascending order, 0 through 60 including the 0 and 60. What RNN filter did you use? I've been using Adobe Audition which has a lot of tools to deal with such things, but I'm not sure if they're really on the cutting edge or not, what you used may or may not be better - would be fun to checkout in any case.

**Comment by bani** [comment]
The filter is [RNNoise](https://jmvalin.ca/demo/rnnoise/). It's open source and there are various plugins based on it.

My solution wasn't the most straightforward. I used OBS, with the filter "Noise Suppression" configured to RNNoise, so I played my wav outputing to a video, and then extracted the audio from the video.

**Comment by bani** [comment]
Unfiltered and uncompressed files are here: https://github.com/bani/online-go.com/commit/28ba34ab274a5a5abf0805ed1b0b67cf710387f4
Let me know if it needs any changes.

**Comment by bani** [comment]
Actually, I think my other microphone has better quality. Please try this one instead: https://github.com/bani/online-go.com/commit/f2a7b5dd74d8103cb0b516cfa5af035b68c732f7

**Comment by BHydden** [comment]
😄 

![image](https://user-images.githubusercontent.com/28991649/159209133-963ce797-0c3c-4d0a-a0b3-459eb98298fc.png)

**Comment by anoek** [comment]
These sound great @bani thanks! Sorry for the delay, been a bit out of commission on my end this past week.. might still be a bit slow this next week too by the looks of it, but I should be able to get these processed and integrated. Thanks again for doing this!

**Comment by anoek** [comment]
Nevermind @bani, I figured out how to clean that up, no need to re-record :)

**Comment by bani** [comment]
all right! I did some reading today and apparently I should have tried talking through my kitchen mesh strainer 😂 
I can try that if you'd like, but if you are almost done with the cleaning then it'll just be extra work.

**Comment by anoek** [comment]
Hah, that might very well have worked if it's a fine mesh strainer - but no need, I think it cleaned up nicely. Want to head over to https://beta.online-go.com/settings/sound and run through the phrases to make sure we got the mapping correct, and make sure you're happy with it? (Note "Start Counting" is always a sound effect so it's expected it'll be little blips)

Thanks again for doing this! You're a permanent site supporter now FYI :)

**Comment by bani** [comment]
Yes, it's all mapped perfectly and sound good :)

Thank you ❤️

**Comment by anoek** [comment]
Excellent, it's up on the main site now. Thanks again @bani!
