### ISSUE TITLE
Intermittent 502 errors

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#175]
Sometimes on the home page, I get a blank error popup and it thinks I have no games going, although I have two.

Sometimes when looking at RoyalLeela's profile to see her current games, I get a blank page in the center portion where all of that would be. Screenshot of the console shows some 502 error messages:

http://puu.sh/uQem2/a529afd7db.png

Also when reloading the profile a moment ago it told me User Not Found, but then a refresh brought it back up correctly again.

**Comment by juanchodepisa** [comment]
I've noticed that several pages bug out in times of high traffic (say 1300+ online users). Either they don't load or load only partially showing a blank error. It makes it really difficult to use the server. 

However, at the same time, I couldn't be sure that's the cause, since other times seems to work just fine or just with a tiny bit of lag.

It's more or less the same when my connection is deficient: pages fail to load, but error messages are not very telling. My point is that I can't tell the difference between network problems on my side or the server's side, but maybe you should explore those possibilities.

**Comment by anoek** [comment]
Should be behaving better nowadays
