### ISSUE TITLE
StrictMode complains about ReactResizeDetector usage

### ISSUE THREAD

**Issue by benjaminpjones** [online-go/online-go.com#1817]
**Describe the bug**

I came across this when investigating #1816 .  It appears to be unrelated, but worth digging into at some point.

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of ChildWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
div
ChildWrapper@http://localhost:8080///ogs.js:134068:20
ResizeDetector@http://localhost:8080///ogs.js:134145:20
div
div
div
div
Game@http://localhost:8080///ogs.js:205717:80
Routes@http://localhost:8080///ogs.js:135865:7
ErrorBoundary@http://localhost:8080///ogs.js:174472:9
div
Main@http://localhost:8080///ogs.js:201828:1
Router@http://localhost:8080///ogs.js:135803:7
HistoryRouter@http://localhost:8080///ogs.js:134709:7
ForceReactUpdateWrapper@http://localhost:8080///ogs.js:238527:69 react-dom.development.js:86
    React 4
    ResizeDetector ResizeDetector.js:78
    ResizeDetector ResizeDetector.js:63
    componentDidMount ResizeDetector.js:221
    React 8
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    (Async: EventHandlerNonNull)
    js scheduler.development.js:571
    js scheduler.development.js:633
    Webpack 25
```

**To Reproduce**
1. Enter responsive design mode
2. Go to any game on OGS
3. Observe the page freezing due to strict mode error.  There will be errors in the console.

**Expected behavior**
The page to continue to function/no strict mode error.

**Screenshots**
<img width="856" alt="Screen Shot 2022-05-03 at 7 07 14 AM" src="https://user-images.githubusercontent.com/25233703/166468786-c49cdd82-5683-4494-ab19-94e1ccddc92c.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Firefox

**Comment by anoek** [comment]
https://github.com/maslianok/react-resize-detector/issues/208 is the issue that I think tracks the class based support issue

**Comment by maslianok** [comment]
react-resize-detector v7.1.1 updated to support React 18.

Thank you for using the library

**Comment by anoek** [comment]
Hey that's awesome, thanks!

**Comment by anoek** [comment]
Ok we're now on the latest react-resize-detector, to complete this issue though we'll need to go through and do what's described in https://github.com/maslianok/react-resize-detector#refs to add refs appropriately to the places we still use the ReactResizeDetector component - which in some places, since we were using the ref ourselves, I think means we will need to switch using the ref handed back by ReactResizeDetector instead of our own created with React.createRef (which should both be the same thing under the hood I think, so shouldn't be an issue.. just takes doing and checking to make sure things are still working).
