### ISSUE TITLE
Provisional account "until X more games have been played" message does not update after playing games

### ISSUE THREAD

**Issue by msayson** [online-go/online-go.com#182]
### Summary

*Briefly describe the issue you are reporting*

New users see the message "Note: This account is currently marked as provisional until X more games have been played" on their profile page.  However, this message is still displayed with the same number after both losing and winning ranked games.

### Environment

 * Operating system: Debian Linux 9.0
 * Browser: Firefox
 * Browser Version: 45.8.0

### Steps To Reproduce:

1. Log in as a provisional user (have just created an account, or have only played a few games)
2. Click on the "Home" tab
3. Click on the "View and edit profile" link
4. See the "Note: This account is currently marked as provisional until 2 more games have been played" message
5. Lose one or more ranked games
6. Return to the profile page
7. Observe that the message has not changed
5. Win a ranked game
6. Return to the profile page
7. Observe that the message has not changed

### Additional Information:

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*

**Comment by msayson** [comment]
If a developer can state what provisional status is really based on, I'd be happy to submit a pull request with an updated message.

**Comment by anoek** [comment]
There's one more factor that goes into reducing this count, the ranked games must be played against another non-provisional player, otherwise it's effectively a non-ranked game and doesn't decrement this count. (This behavior will be altered in the future as we make some improvements to the ranking system, but for the time being, this is how it works.)

Feel free to re-open if the game(s) you played were not against another provisional player.
