### ISSUE TITLE
Bots should be better identified

### ISSUE THREAD

**Issue by mark5000** [online-go/online-go.com#188]
### Summary

There's been several mod reports mistaking bot players for real human players. The general consensus of users in the forum is that bots are not identified clearly enough in game or otherwise. See https://forums.online-go.com/t/who-is-she/11433 In fact, there's absolutely no indication anywhere on the game page that a player is a bot. That creates confusion.

There's several possible ways to make it clear on the game page who is a bot player:

1) The name can be displayed in gray rather than blue;
2) The flag can be replaced with a bot icon; (why do bots have a nationality anyway?)
3) The letters "AI" or "CPU" or "BOT" can be added after the rank, like how "T" stands for timeout;
4) The word "AI" or "CPU" or "BOT" can be added to the blank space to the right of the user icon.

I'm not advocating any particular solution here, but something similar to one or multiple of the above should be implemented.

### Environment

All devices and browsers.

### Steps To Reproduce:

1. Go to any bot game, such as https://online-go.com/game/8201519
2. See that there is no indication whatsoever that either player is a bot.

### Additional Information:

This is the current bot player badge. Notice how it's got an icon just like a human player, a name that does not necessarily suggest bot use, and even an American flag in the lower corner. You can't tell it's a bot unless you know about the Leela program, and even then the name could be coincidental. That's asking for confusion.

![bot-default](https://cloud.githubusercontent.com/assets/13010650/24439835/949d7e20-1405-11e7-8eaa-6b9004b94629.png)

**Comment by top106** [comment]
Well, but... PtoP is my id and not a bot.

**Comment by roy7** [comment]
Hah we both had the same ideas. :) https://github.com/online-go/online-go.com/issues/187

I think what has prompted this is the Kyu Player bot. He doesn't just run the bot in the "Play Vs Computer" drop down, he actively makes open challenges by hand which people then accept, not realizing it is a bot. I've never done open challenges / tournaments / ladders with RoyalLeela because of that reason, people should only end up with games vs bots if they intentionally choose to be, I imagine? I also don't accept other people's open challenges with the bot, I figured that'd be quite rude.

**Comment by BarneyStratford** [comment]
From a UI perspective, if a player wanted to play a bot, the’y have challenged the bot. Issuing an open challenge is explicitly a request to play a person. I guess it’s actually a bug that bots *can* accept open challenges. Unless anyone has better ideas?

Barney.

**Comment by anoek** [comment]
Closing in favor of tracking the fix in #190
