### ISSUE TITLE
BUG: Malkovitch chats visible during game if not logged in

### ISSUE THREAD

**Issue by nickeubank** [online-go/online-go.com#202]
I'm playing a malkovitch game and discovered by accident that if you visit a game when not logged in, one can see all messages in real time (I.e. while game in progress). Probably undesirable...

**Comment by roy7** [comment]
It was an intentional choice that the logs are visible to everyone except the opponent.

However, it might be useful to make it hidden to opponent and people not logged in to make cheating harder.

**Comment by nickeubank** [comment]
Seems reasonable. You could even restrict to non-provisional players if you really wanted, though I think limiting it to people with active accounts who are not the opponent would be sufficient. :)

**Comment by BarneyStratford** [comment]
I’m not sure that restricting the log would help. If you restrict it to registered or non-provisional players, then there’s nothing to stop someone from logging in as a second player and looking at the log. I think there are two choices here: leave as-is so that spectators can gain the maximum benefit from the logs; or hide the logs to everyone, including the spectators, until the match is over. Or some combination of the two.

**Comment by Spoekenkieker** [comment]
> there’s nothing to stop someone from logging in as a second player and looking at the log.

Well, I’d think this is a risk we can take (a risk that _I_ personally would take, being someone who often uses the M log).

**Comment by anoek** [comment]
Yep, it was a decision based on overwhelming feedback from the community. The summation is, if you're doing a malk log, you're probably doing it with someone you're not concerned about cheating with. However viewing the malk log for long running games is something that spectators like to do, and since we've decided we're not concerned with your opponent cheating, then there's no particular reason to try and make cheating harder by making it so it's only visible to people logged in / non provisional players, whereas restricting it to those people would make it hard for non OGS'ers to come by and check out some high profile game that they were linked to or something of the sort.
