### ISSUE TITLE
Feature-Request: Need bookmark button when watching game

### ISSUE THREAD

**Issue by ggpp23** [online-go/online-go.com#206]
### Summary

I need to have the ability to bookmark a game I'm watching.
Currently I'm hijacking the functionality of "review game" to keep track of the games I like.
It would be better to bookmark games, puzzles, users and have a bookmarks page in home or profile.
Browser's bookmark is not useful since it will store the bookmark only on the machine I'm currently using.

**Comment by benjaminpjones** [comment]
>Browser's bookmark is not useful since it will store the bookmark only on the machine I'm currently using.

This makes me think this issue needs the "api support" tag.

Although so many browsers offer the ability to access bookmarks across machines, I'm wondering if this request is obsolete...

**Comment by ggpp23** [comment]
Online-go already has the ability to "save a game for review". The game is
saved into my "personal page" inside online-go webservice.

What I had in mind was the ability to "save a game link with an associated
comment" also stored into my "personal page" inside online-go.
Maybe the comment can be "pre-populated" with the names of the players that
participated in the game. I would choose to edit this comment to something
more significant for myself in some cases.

The benefit would be that when I search for a game I "bookmarked" I can
scan through my comments instead of looking at those numeric gameIDs that
are currently used to identify each game.


Giuseppe G.

**Comment by benjaminpjones** [comment]
I guess I'm wondering how much value this adds since the following workarounds are available:

1) Most browsers have a bookmarks feature, and many browsers allow you to sync across devices (e.g. [Chrome sync](https://support.google.com/chrome/answer/165139?co=GENIE.Platform%3DAndroid&hl=en), [Safari iCloud Bookmarks](https://appletoolbox.com/how-to-sync-bookmarks-in-safari-across-multiple-devices/), [Firefox Sync](https://en.wikipedia.org/wiki/Firefox_Sync)).
2) You can add named links to your profile page like so:
<img width="565" alt="Screen Shot 2021-02-17 at 12 28 31 PM" src="https://user-images.githubusercontent.com/25233703/108243125-b9c9d500-711b-11eb-9f0b-0b3cf7ab1574.png">

which shows up like:

<img width="560" alt="Screen Shot 2021-02-17 at 12 28 42 PM" src="https://user-images.githubusercontent.com/25233703/108243129-bc2c2f00-711b-11eb-8587-179c4a6cb55e.png">

    

You can
