### ISSUE TITLE
How are the places on the OGS allocated with the same number of points?

### ISSUE THREAD

**Issue by PavelGvozdev** [online-go/online-go.com#2083]
Hi.

Where can I read the procedures for using the MacMahon system on the OGS? In particular, what coefficients are used if players have the same number of points. I could not find this information in the OGS Wiki. 
In this tournament https://online-go.com/tournament/94932 DmKu[13k] took second place in the group, and Flowflo98[16k] first place. DmKu[13k] won all games, and DmKu[13k] lost two games. I am the organizer of the tournament and players ask me why this happened.
Here is a screenshot of the standings: https://disk.yandex.ru/i/eiAoXl1XO8Ab-g

Thank you and have a nice day!

**Comment by juanchodepisa** [comment]
Hi, normal user here (not a dev)

I think you might have better luck asking in the forums, since this space is mostly for bug reports.
I'm quite certain this isn't a bug, there are tie-breaking mechanisms like SOS and SODOS, but can't point out exactly where this is explained (somewhere in the FAQ, or the user manual probably).
