### ISSUE TITLE
Scoring screen not responsive when a border is open

### ISSUE THREAD

**Issue by glyphimor** [online-go/online-go.com#2086]
**Describe the bug**
In [one particular game](https://online-go.com/game/49536076), when we went to scoring w/ an open border, my CPU went to 100% and the page was unresponsive -- the Cancel button didn't work, clicking on groups of stones took 20-30+ seconds to change their status, etc.

**To Reproduce**
Not sure how to reproduce, frankly. Now that the [game](https://online-go.com/game/49536076) is over, the postgame full-featured score estimator works fine. Presumably there's some way for a developer to test the scoring phase w/o replaying the game.

**Expected behavior**
Scoring screen is responsive, cancel button works, CPU isn't at 100%.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser1: Firefox 102.5.0esr
 - Browser2: Chrome 108.0.5359.98

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: iPadOS 16.2
 - Browser: Safari

**Additional context**
While we were still in the scoring phase, I tested multiple browsers and all were similarly unresponsive: Safari on iPad, Firefox & Chrome on Linux.

**Comment by benjaminpjones** [comment]
I was able to reproduce by forking the game, and I can confirm, scoring seems laggy on this board.  On my system, I experience 2-5 seconds on the larger groups.

Dev notes: The relevant function is [`toggleMetaGroupRemoval()`](https://github.com/online-go/goban/blob/a3a906a0927055d6031937379756617428de667e/src/GoEngine.ts#L1562) in goban.

I've noticed in the past that `getGroup()` is O(N) where N is number of intersections in the group. However I don't think that's the issue because N is still relatively small (<361).  Looking at the flame graph, it looks like a big chunk of time is spent in the drawing functions, triggered by:

toggleMetaGroupRemoval > setGroupForRemoval > setRemoved > GobanCore.setForRemoval

Will need to investigate whether the issue is the for loops or the rendering.  I don't think drawSquare should take seconds even if we call it 300 times.

<img width="538" alt="Screen Shot 2022-12-26 at 12 59 14 AM" src="https://user-images.githubusercontent.com/25233703/209529397-7633ad9a-629e-454e-905b-c3144b87e202.png">

**Comment by benjaminpjones** [comment]
> I don't think drawSquare should take seconds even if we call it 300 times.

Turns out we call it much more than 300 times.. I monkeypatched drawSquare in the console to count how many times it's been called, and:

```
var draw_square_count = 0
var orig_draw_square = global_goban.drawSquare.bind(global_goban)
global_goban.drawSquare = (e, t) => { draw_square_count++; return orig_draw_square(e, t); }
```

Then click somewhere to remove stones, and print `draw_square_count` - it's 112215 😳.  That was for a 90 stone group where the lag is noticeable, but even for a 2 stone group, `drawStone` is called 2000+ times.  I think it's safe to say that `drawStone` doesn't need to be called more than 361 times for a single action.

I haven't accounted for exactly where all those calls come from, but it looks like the problem is that we emit `"stone-removal.updated"` many times (once for every intersection that gets toggled), and each time we compute a couple expensive functions - `computeScores` + `showScores`, which in turn calls `drawSquare` many times (potentially the whole board).

**Comment by BHydden** [comment]
Heck even if we emitted `stone-removal.updated` every millisecond it would still be a huge performance improvement (if for some reason figuring out when "the very end" is were some theoretical complication)

**Comment by kobakitty** [comment]
I guess this is the reason why espesially larger boards are so slow in stone removal? When finishing a 25x25 game it can take well over 10 seconds before the board reacts in any way after clicking some group (and thats with laptop, on mobile it takes even longer xD)
