### ISSUE TITLE
Max moves for "game annulled"

### ISSUE THREAD

**Issue by piskvorky** [online-go/online-go.com#212]
The number of moves during which the game is annulled is too high: 19 moves according to [this forum thread](https://forums.online-go.com/t/annulled-games-question/1669/9). That is, if the opponent escapes/times out within the first 19 moves, the game doesn't count.

On the forum, `pbgarden` (I assume a mod) says *This seems to be largely accepted by the community, and has been the case for a while now. I wouldn't anticipate this changing, as "escaping" like this seems to be a pretty rare occurrence.*. But that doesn't seem to match my or other people's experience (see the other comments in that thread).

Any reason not to use a saner number of max moves for game annulment, like 5-6? For example, KGS uses 10 moves max, AFAIK.

**Comment by mlopezviedma** [comment]
The reason was technical, and it's no longer needed. This is planned to change, 2 will be the magic number for all board sizes. Not yet too high priority though.

**Comment by piskvorky** [comment]
Thanks @mlopezviedma , that's great news!

I have to say, "the reason was technical" is a nice teaser. Now I wonder, what kind of technical reason would make a system make the number of moves before annulment be fixed? Isn't it just a constant defined somewhere? :)

**Comment by Saxmaam** [comment]
Great news!

**Comment by anoek** [comment]
@piskvorky a long long time ago we implemented pre-defined handicaps by "playing them out" in the moves string (now array), so we'd literally record a move on each applicable star point followed by a pass. Maximum handicap that we cared about was 9, so 18 fake moves, so the annulled number needed to be higher than this ;)

Anyways that was a horrible way of doing things and now we just have an "initial state" we set the board to, so that can be reduced, it's basically pretty far down the list though and I'm not confident about what the number should be.

**Comment by anoek** [comment]
This has been implemented and will be active as the glicko2 stuff roles out
