### ISSUE TITLE
AI projected optimal branch view can be quite cluttered

### ISSUE THREAD

**Issue by andymarden** [online-go/online-go.com#2248]
As an option to "Show only next move in AI review" would be really useful.

**Comment by andymarden** [comment]
Gonna pick this up and give it a go. Will:

1. Add new option in game settings called "Max AI Moves to Display"
2. Defaults to 0 (ie as much as the default)
3. Change the code that works through the list of moves in the branch and choose the next n where n is the value entered above (of n is not zero)

Haven't looked at the code yet but it seems that should be straightforward enough.

**Comment by benjaminpjones** [comment]
I haven't looked into it closely, but it sounds like this may touch Goban code too.  Goban is a separate repository (https://github.com/online-go/goban).  When working with goban, [yarn link](https://classic.yarnpkg.com/lang/en/docs/cli/link/) can be a useful tool to link to a local version of the package instead of the one on npm.

Here is a related set of PRs for the transparency setting of these variations, maybe there are  some useful code pointers: https://github.com/online-go/online-go.com/pull/1317, https://github.com/online-go/goban/pull/19
