### ISSUE TITLE
Preference for defaulting chat mode on the game page

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#2273]
[From the forum](https://forums.online-go.com/t/default-chat-preference/48072?u=greenasjade):

Is it possible for users to set the chat preference to “personal or Malkovich chat” as the default option? This would be greatly appreciated, especially for users with multiple games, as it would eliminate the need to constantly toggle the chat setting whenever they click on the chat button.

I fear of forgetting to toggle chat, so my evil plan gets accidentally leaked to my opponent :person_facepalming:

**Comment by andymarden** [comment]
Picking this up

**Comment by andymarden** [comment]
OK - dev is done:

You can select default chat mode on the Game Preferences (Chat, Malkovich, Personal) so that when you start any game, that is what it will come up with.

If you change the mode while playing, that is the mode used.

But, if you exit the page and refresh, it will go back to the default you have set.

Before I commit the changes, is that last bit the required behaviour (rather than it remembering the last mode you set in that particular game)? Hint - I'm done if you say yes!

**Comment by GreenAsJade** [comment]
That sounds right sensible to me.

Often, I've found it useful to ask in the forum ... usually about half the people will violently disagree with you, but if the objection rate is slightly less than 50% then you know you're on the right track 😝

**Comment by andymarden** [comment]
Think I'll go with it - given the driver for the change - not to accidentally be in a mode you don't want, then defaulting to the preference is the right thing.
