### ISSUE TITLE
Allow branches to be instantly copied from 'Analyze Mode' to 'Conditional Move Planner', or merge the Analyzer with the Planner

### ISSUE THREAD

**Issue by Nazgand** [online-go/online-go.com#239]
It is not uncommon for me to make plans in 'Analyze Mode', and then manually copy them to the 'Conditional Move Planner', move by move. After all, if I tested branches while in the 'Conditional Move Planner', I would have to delete often.
It would be nice to be able to click a button to make a branch in 'Analyze Mode' to make the branch a conditional move plan.
If we add this feature, we may as well also show in 'Analyze Mode' which branches are conditional move plans by highlighting them and moving them closer to the main branch than everything which is not a conditional move plan.
Then may as well have a button in 'Analyze Mode' to remove a move and its branches from the 'Conditional Move Planner'.
At this point, we can remove the 'Conditional Move Planner' because all of its features have been absorbed by 'Analyze Mode'. Another advantage to merging the Analyzer and the Planner is that it would allow conditional move plans that can deal with passes.

**Comment by lemurek** [comment]
I'm generally not playing long games that would require using move planner, but it does seem satisfying minimalistic to be able to use a single analysis tool, than jumping between two of them. It should indeed be as simple as having a button 'I like this variation - make this automatic' - there seems to be no need for another tool

**Comment by hzamir** [comment]
I just added feature request #1030 to accomplish pretty much the same thing but instead allowing you to make your response with conditional move planner.  I first thought like @Nazgand, to somehow submit moves and plans from the analyzer, but I think that turns out to be more complicated. I probably wouldn't bother all that much with the analyzer during a game I'm playing when conditional move planner can handle it.  The only thing that might need additional improvement is to require approving each branch in the planner, rather than requiring you delete sequences which don't work.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
