### ISSUE TITLE
Ratings and rank ±error bars are 2x smaller than Glicko-2 says they should be

### ISSUE THREAD

**Issue by dexonsmith** [online-go/online-go.com#2509]
From the [Glicko-2 paper](http://www.glicko.net/glicko/glicko2.pdf):

> One way to do this is to report a 95% confidence interval. The lowest value in the interval is the player’s rating minus twice the RD, and the highest value is the player’s rating plus twice the RD. So, for example, if a player’s rating is 1850 and the RD is 50, the interval would go from 1750 to 1950. We would then say that we’re 95% confident that the player’s actual strength is between 1750 and 1950.

RD in Glicko-2 corresponds to `deviation` in the code.

When we display ratings/ranks, we're currently doing something akin to the following:
- rating: `{r.rating} ±{r.deviation}`
- rank: `{toRank(r.rating)} ±{toRank(r.rating + r.deviation) - toRank(r.rating)}`

But the example from the paper introduction suggests the following, instead:
- rating: `{r.rating} ±{2*r.deviation}`
- rank: `{toRank(r.rating)} ±{toRank(r.rating + 2*r.deviation) - toRank(r.rating)}`

I believe this is just a display issue.

**Comment by dexonsmith** [comment]
@anoek, I'm happy to fix this, but assigning to you first to confirm whether this was intentional.

**Comment by anoek** [comment]
He's basically just spelling out how to interpret the application of the standard deviation in this context. In really brief summary, you should expect 68% confidence that the rating is between rating +- deviation, 95% that it's between rating +- 2x deviation, 99.7% within rating +- 3x deviation. There's not a wrong and write answer in this case as it's informational (it's not like we're tossing out outliers or anything after all, we're just using this as a rough gauge of someone's strength). Since it's just informational, it's largely subjective I feel, and personally I feel like looking at the 1st standard deviation feels better. We certainly don't care about the 3rd standard deviation (who care's if we're 99.7% sure that someone is between 20kyu and 7dan right?). In the same vein, I think the 2nd is less interesting than the 1st in this case I think.

**Comment by dexonsmith** [comment]
Okay, right... seems fair!
