### ISSUE TITLE
Cannot pass in Conditional Move Planner

### ISSUE THREAD

**Issue by Nazgand** [online-go/online-go.com#251]
Being able to respond to a pass automatically would be nice, and being able to respond with a pass would also be nice.

**Comment by BHydden** [comment]
Almost certain this is resolved

**Comment by anoek** [comment]
It is not :(

**Comment by BHydden** [comment]
Oh... Umm, could it be?

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.

**Comment by BHydden** [comment]
Reopening based on forum [discussion](https://forums.online-go.com/t/passing-when-planning-conditional-moves/1160/37?u=bhydden) .

**Comment by benjaminpjones** [comment]
Thanks for reopening @BHydden.  So I've made a few PRs that prep for this feature (most importantly https://github.com/online-go/goban/pull/80), and in fact, it is possible to get something basic in now with one line:

```
                        <button className="primary" onClick={acceptConditionalMoves}>
                            {_("Accept Conditional Moves")}
                        </button>
+                        <button onClick={() => goban.pass()}>{_("Pass")}</button>
                        <button onClick={goban_setMode_play}>{_("Cancel")}</button>
```

<img width="380" alt="Screen Shot 2022-08-27 at 8 03 47 PM" src="https://user-images.githubusercontent.com/25233703/187055636-55d9e098-3f1c-4085-a20f-5328df9f99a9.png">

I think there are a few other UX items that would need to be addressed in order to be production quality:

- "pass" needs to be internationalized in the tree
- Do we need to confirm with the user as is done in regular passing? If so, when?
    - When the pass button is clicked
    - When the accept button is clicked, and there is at least one pass played by the user in the tree
- Is that pass button too prominent? How many complaints will we get from folks who don't want conditional pass?

**Comment by BHydden** [comment]
> "pass" needs to be internationalized in the tree

I wonder if that might happen automatically, since the string as been translated elsewhere? 🤔

> Do we need a confirmation dialog as is done in regular passing?

I think not, since users already have access to the red x for branches and the blue accept button. That is surely confirmation enough.

> How many complaints will we get from folks who don't want conditional pass?

People who don't want to pass won't pass... am I being too optimistic to think there is nothing to complain about? 🤔🤷‍♂️

**Comment by benjaminpjones** [comment]
> am I being too optimistic to think there is nothing to complain about? 🤔🤷‍♂️

Yes, yes you were 😆 https://forums.online-go.com/t/passing-when-planning-conditional-moves/1160/48
