### ISSUE TITLE
UI improvment, Change mute-button location when sidemenu expands

### ISSUE THREAD

**Issue by sousys** [online-go/online-go.com#254]
### Summary

Today, if you want to mute sound on a game and you go for the mute/volume-icon in the right side menu, the menu expands and effectively moves the thing you want to click on; the mute-icon/button.
It would be preferable if the mutebutton/icon stayed put while the menu expanded outward

### Steps To Reproduce:
* open a game-board
* try to mute the sound.
* Watch the thing you want to click on troll you

**Comment by Nazgand** [comment]
I never considered this as a problem, but I see your point now. If I want to open 'Analyze Game', I can click where the icon was before it moved left.
If this problem is fixed, I think it would be best to do so by moving the vertical icon bar to the left side of the screen so that the icons stay on the left side of the text and do not move as the text appears/disappears OR move the icons to the right side of the text such that they do not move as the text appears/disappears.

**Comment by anoek** [comment]
Yeah the current experience is suboptimal. Perhaps the text moving but keeping the icons stable would be better, I'd have to see it in action I reckon.

**Comment by BHydden** [comment]
The mute button is the only button that isn't clickable from anywhere inside the whole element. Assuming it doesn't break the volume slider, I think changing it so that any click outside the slider toggles mute should do the trick
