### ISSUE TITLE
Submit move and pass button are currently overlapping

### ISSUE THREAD

**Issue by mraraujo** [online-go/online-go.com#274]
### Summary

I have a mini heart-attack every time I submit a move and I'm taken to the next game. 
The "submit" button (of the previous game) and the "pass" button of the new game occupy the same position. I often play on my laptop and double tap on the touchpad, so it's very easy for me to click twice in succession by accident, even though I think the pass button has a confirmation dialogue (not sure).

Could the pass button be moved (and resized) to the side of the resign button? They are fairly similar, even functionally wise, so it would make sense that they share the same size.

**Comment by anoek** [comment]
I'm open to some conversation about a better location, but we tried the side bar a long time ago and the location was strongly rejected by folks because in blitz and live games it needs to be accessible quickly.

I'm going to close the issue here as any move should involve an open discussion about where the button should be placed, and that discussion should happen on the forums. If in that discussion some general consensus can be reached, then a new issue can be opened to track implementing the change.
