### ISSUE TITLE
Rapid moves fail to register

### ISSUE THREAD

**Issue by frostburn** [online-go/online-go.com#2838]
**Describe the bug**
Clicking the board in rapid succession _"eats"_ most of the moves.

**To Reproduce**
1. Go to Tools -> Demo Board
2. Rapidly click around the board randomly
3. Only a fraction of the clicks actually register

**Expected behavior**
User input is buffered and unrolled onto the board while the network/compute catches up.

**Screenshots**
![image](https://github.com/user-attachments/assets/521e59c7-59c7-4bd3-b752-9c7cfa8ea8a1)
Screenshot of the board after a burst of around 40 clicks using the mouse. Notice how there are less than 40 stones on the board.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser: Chrome
 - Version: Version 128.0.6613.113 (Official Build) (64-bit)

**Additional context**
The issue is exacerbated with AI review turned on.

**Comment by anoek** [comment]
My first suspicion is that the anti-slip code is what you're running into, not any failure to register. The slip code basically said if you click and move your mouse too much, we don't do anything with the move, it's there to help prevent accidental moves.

Feel free to re-open this if it's not the issue but otherwise I'm inclined to close this because the anti-slip code is good in practice and won't be sacrificing it in order to be able to splatter down stones super fast.

**Comment by frostburn** [comment]
Fair enough. At least now I know there's a reason for this behavior. I guess I just need to stabilize my clicks if I want to play faster. Thank you for the quick reply.
