### ISSUE TITLE
Generate desktop notifications when it becomes your turn in a game

### ISSUE THREAD

**Issue by anoek** [online-go/online-go.com#301]
### Summary

In v4 we used to generate desktop notifications when it became your move on a game. This never got re-implemented as we changed how the turn notification stuff worked. It should be re implemented, and likely some configuration options added under settings for the feature.

**Comment by nclavaud** [comment]
Do you mean sending notifications using the [Push API](https://developer.mozilla.org/en-US/docs/Web/API/Push_API)?

Because this would be a great (optional) alternative to emails. And it would render nice, native-like notifications on mobile.

I see there are several other issues about notifications (see #59, #241, #242, #245) that could benefit from this as well.

I'm keen on working on this but it would also require changes on the API side.

**Comment by BHydden** [comment]
I believe this has been implemented now.
