### ISSUE TITLE
Changing time controls from canadian to byo-yomi in rematch screen is ignored

### ISSUE THREAD

**Issue by msmsajjadi** [online-go/online-go.com#314]
Here's a case where it always fails:
1. Click Play -> Computer. Select settings in this order:
  - engine: fuego
  - board size 9x9
  - game speed: blitz
  - time control: canadian
  - leave the rest unchanged (settings here: 10s+5*10s, handicap none, komi custom 5.5, color automatic)
2. Click Play.
3. Click cancel game. Yes.
4. Click rematch. Don't touch anything but change time control from canadian to byo-yomi. Click send challenge.
**5. Game starts with canadian time control.**
6. Cancel game gain.
7. Hit rematch. **Settings are the old ones with canadian time control.**

It seems to only happen when going from canadian to byo-yomi.
Browser: Latest Chrome. Cookies enabled.

**Comment by seaotterman** [comment]
Since I'm having difficulties reproducing it in different scenarios, here's the case where it always fails:
1. Click Play -> Computer. Select settings in this order:
  - engine: fuego
  - board size 9x9
  - game speed: blitz
  - time control: canadian
  - leave the rest unchanged (settings here: 10s+5*10s, handicap none, komi custom 5.5, color automatic)
2. Click Play.
3. Click cancel game. Yes.
4. Click rematch. Don't touch anything but change time control from canadian to byo-yomi. Click send challenge.
**5. Game starts with canadian time control.**
6. Cancel game gain.
7. Hit rematch. **Settings are the old ones with canadian time control.**

It seems to only happen when going from canadian to byo-yomi.

**Comment by Adam314159** [comment]
Seem to not be connected with only canadian Time. Rematch just ignores the changes made to clock.

Also discussed briefly here:
https://forums.online-go.com/t/rematch-request-time-settings-glitch/25015
