### ISSUE TITLE
Forgetting to submit move is too easy.

### ISSUE THREAD

**Issue by Nazgand** [online-go/online-go.com#317]
I have done it to others, and other have done it to me. I don't know the best way, but here are some ideas:
Visible difference. maybe the entire board changes color until the move is submitted, maybe the stone glows or is transparent or a different color before it is submitted.
Audible verification: we could have a sound that means the move is submitted.
Timeout: if the move is not submitted after e.g. 3 seconds, then it disappears and a sound is played to alert the player.

I think the Timeout option is the best, but discuss.

**Comment by anoek** [comment]
We used to gently strobe the color of the button to draw attention to it, I guess I never added that back in. If done again, it should be a setting that folks can turn off, some people liked it, others found it very distracting.

I don't think the timeout disappearing the button would be well received, lots of folks place a stone and take a look at the board for a bit before committing to it by hitting submit, so that'd be very annoying for them.

**Comment by mlopezviedma** [comment]
Should this one be closed in virtue of the new "+" mark?

**Comment by anoek** [comment]
Yes, thanks :)
