### ISSUE TITLE
From times to times we see right rating with wrong rank

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#363]
### Summary

Amongst games where it's my turn, I'm switching from one to the other by the mean of the little black circle.

And, from times to times, I can see, for some games but not all, my previous rank with the correct rating. When I reload the page, it gets fixed on its own but the incoherence quickly reappears sometimes for the same games, sometimes for different ones. 
I haven't tried to empty my cache, and I haven't tried yet on my workstation.

### Environment

 * Operating system: Android 7.0
 * Browser: Firefox
 * Browser Version: Firefox 54.0.1

### Steps To Reproduce:

ask if needed

### Additional Information:

![right-rating_wrong-rank](https://user-images.githubusercontent.com/26174230/27840024-a9f921fe-60ed-11e7-8bed-e1f7c51d38d2.png)

Arnaud

**Comment by anoek** [comment]
Yeah for better or worse the game page displays the rank of the player when the game started for historical perspective.. that way when you look at a dan player's game 5 years ago, you can see they were really 12k when they played a game. It'd probably be a good thing to come up with some way of indicating their past and present rank to help avoid confusion.. without being more confusing.

**Comment by BarneyStratford** [comment]
What about displaying “n Kyu” if the user is still n kyu, and “Was n Kyu” or “Formerly n Kyu" if he isn’t?

Barney.

**Comment by anoek** [comment]
Indeed, might be the best way of handling it

**Comment by arnaudgo** [comment]
@anoek, actually, I had spotted that but the issue I wanted to raise is that my "15 kyu" you see in the screenshot I enclosed, turns into a "14 kyu" after a refresh. The rank value should be persistent, whatever if it's the rank before or the rank after.

:-)

Arnaud

**Comment by anoek** [comment]
bah, I guess we changed that, or I'm just making stuff up. It *should* work that way.. tbh i don't know if that's a v5 regression now or if we changed that at some point long ago.

**Comment by anoek** [comment]
mm, now i'm remembering something about changing the behavior because people's ranks can change (significantly, and many times) during the course of a game with corr. games. That was in v4..

I suspect the most-right-while-not-being-horribly-complicated answer would be to display their current rank if the game is still in progress, or the recorded rank if the game is finished? and update the recorded rank at game end.

**Comment by BarneyStratford** [comment]
I’m not so sure. The details on the popover should always be the current ones, no? If we combine that with my earlier suggestion, then it should make it unambiguous.

The stuff on the popover comes from the player_cache, not from the current game. If it’s appearing wrong in the popover then it’s wrong in the cache, and is going to appear wrong after leaving the game in question as well. I’ll bet it’s being written to the cache somewhere where it shouldn’t be.

barney.

**Comment by anoek** [comment]
My interpretation was that the 14k was the current, sot he popup details were/are indeed correct and up to date.

I like your idea, the question I was pondering in my rambling was how to best deal with the case when a game is ongoing but the player's rank has changed during the course of the game. So for instance, if i'm playing in a month long game and my rank has changed during that time, it might be weird(ish) to see "anoek (was 18k)" while the game is still in progress .. though maybe not. Regardless there's also the question of what to display as the game concludes, should the rank that I was when the game started be used and stored, or should my rank at the conclusion of the game be used? (And, should it be the rank prior to rating change due to the game, or after?) So my gut says, just display the users current rating while the game is in progress, then when the game ends, store the rank just before adjusting a rank, and from then on out display that rank with your "was Nk" system.. but certainly open to arguments for a different way of dealing with that

**Comment by BarneyStratford** [comment]
Ooh, I like that.

Barney.
