### ISSUE TITLE
In chat, the text is wrapped in the middle of the words

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#382]
### Summary

In chat, the text is wrapped in the middle of the words rather than at the end.

### Environment

 * Operating system:  Android
 * Browser: Firefox
 * Browser Version: 54.0.1

Also on Chrome/ 59.0.3071.125

### Steps To Reproduce:

ask if needed

### Additional Information:

![chatroom-chrome](https://user-images.githubusercontent.com/26174230/28434978-40bbb762-6d89-11e7-8531-9ce238335fee.png)
![chatroom-firefox](https://user-images.githubusercontent.com/26174230/28434983-45bd3b3c-6d89-11e7-96ab-16257a14ff52.png)

Arnaud

**Comment by arnaudgo** [comment]
Also occurs on my desktop (Firefox same version)

**Comment by anoek** [comment]
So the reason for this is because it doesn't appear to be possible to tell the browser to break up words like that when *necessary* but not otherwise, it's an all or nothing thing: https://www.w3schools.com/cssref/css3_pr_word-break.asp

If we leave that to normal, it behaves more like how you would want and expect, but when someone comes along and types a long sequence of letters without any hyphens or spaces, the whole chat window expands to fit that text and pushes the user list off. My attempts to hide or otherwise mitigate that problem while preserving "good" text cases have failed.

I would love for someone to show me the way here and come up with a better solution, but I've tried a few times now and this is the best I've got.

**Comment by arnaudgo** [comment]
No way to fix a max-width to prevent it?

**Comment by anoek** [comment]
Not that I could get to work.. there has to be a way, slack does it just fine, I dunno I'll try again in a bit. Probably just something stupid..

**Comment by BarneyStratford** [comment]
I have an idea for this one. Could we use word-wrap:normal and insert &shy; periodically inside very long words? That would certainly work in the English chat, but might cause problems for agglutinative languages like Hungarian or Finnish.

Barney.

**Comment by anoek** [comment]
OK looking at it again, `max-width` with some `calc` worked, just had to try harder :) Thanks for the push.

**Comment by arnaudgo** [comment]
Good job!
