### ISSUE TITLE
Pros rank not showing right in game chat messages (glicko-2)

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#405]
Issue #136 seems to be back. Perhaps from the glicko-2 changes? If you check a game where Ten speaks in chat, it shows as 8d again instead of 1p.

**Comment by anoek** [comment]
This is a historical bug that has been fixed, recent games and reviews should work as expected

**Comment by anoek** [comment]
The reason why this was "working" before is because we were doing extra user data fetches, but that was in fact a bug, we want to display the ranks players were when they made the comment. Unfortunately that surfaces this issue, where we weren't logging the `professional` flag appropriately in chat messages, and thus they wont render right now.

**Comment by roy7** [comment]
Probably not worth the hassle and can leave old messages alone to avoid extra data fetches. But one solution could be to just iterate over each account with pro rank, and set the professional flag to true for all past logged messages by that person. A one time pass to fix all past history. I'm not sure if the database makes that sort of query easy or difficult though.
