### ISSUE TITLE
Kindle chat

### ISSUE THREAD

**Issue by Tomewing1** [online-go/online-go.com#419]
### Summary

Ever since the OGS upgrade, I've been unable to use the "chat" feature on my Kindle Fire.  I was hoping that in time, having reported the problem in Forum that it would be fixed.  Months have gone by but nothing.  I have used the chat feature often in the past but can no longer.

### Environment

 * Operating system: 
 * Browser:
 * Browser Version:

### Steps To Reproduce:

1. Go to ...
2. Click ...
3. See that X wrong 

### Additional Information:

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*

**Comment by anoek** [comment]
As I have no Kindle Fire to test with, it's not possible for me to fix this issue without significant help from you or from someone else with a Kindle Fire.

If you can provide to me some error messages and stack traces obtained from whatever debug system the Kindle Fire's Silk browser has, then we might be able to fix it.

Otherwise, if you download the Firefox or Chrome browsers, those should just work on your kindle fire.

**Comment by anoek** [comment]
I'll be closing this issue in 3 days unless someone wants to provide some more details
