### ISSUE TITLE
Date sort puts games with opponent on vacation at the very top

### ISSUE THREAD

**Issue by apetresc** [online-go/online-go.com#424]
### Summary

When you have the game list sorted by date, games where the opponent is on vacation appear to be stuck to the very top no matter how much time is actually remaining. For example, this screenshot:
![](http://apetresc-screenshot.s3.amazonaws.com/2017-08-23-21:31:08.png)

At least, I'm _assuming_ it is my opponent's vacation flag that is causing this unexpected sort, obviously the game with 6 hours left should be at the top. If anything, games where the opponent is on vacation should be at the very _bottom_ of the list, since they require the least immediate attention.

I've lost games on time because in thumbnail view, a quick glance at the top row or two didn't show any games where I was in danger of timing out, because of lots of opponents on vacation, but there was one lurking right beneath the fold :(

### Environment

 * Operating system: Arch Linux
 * Browser: Chrome
 * Browser Version: 60.0

### Steps To Reproduce:

1. Sort by Clock
2. Have a game where the opponent is on vacation
3. See it at the very top regardless of how many other more urgent games there are.

**Comment by anoek** [comment]
Hmm, I'm having a hard time reproducing this, everything seems to be sorting good for me whether or not opponents are on vacation or otherwise paused =/. There might have been something else going on as well that caused this.

**Comment by apetresc** [comment]
Hm, yeah, there's definitely something weird going on - I can reproduce it quite consistently, although there are some weird wrinkles for me as well. For example, here is my current game list, very recently refreshed:

![image](https://user-images.githubusercontent.com/14872/30245971-474db6d6-95b9-11e7-889c-3ac582d360d5.png)

The Turing tournament respects weekend time, so the first three entries are all from there - even though game 4 against mimano *should* be sorted higher than my game against Peter K, based on time remaining. This would be completely consistent with my assumption that paused games are always sorted first... except for the last game on my move which is also on weekend time, but is sorted correctly at the end. :man_shrugging: 

So, I'm not sure exactly what's going on, but I do know that my game list is very consistently mis-sorted whenever vacations are happening :(

**Comment by BHydden** [comment]
This can be closed. Same issue as #500

**Comment by BHydden** [comment]
I was wrong, the issues were the same, but the problem persists.

**Comment by BHydden** [comment]
![3d06445d-1882-4982-8ac7-0524bdacb206](https://user-images.githubusercontent.com/28991649/206959156-49dbcdfb-4c06-430d-9bbf-090c305e9fc8.jpg)
Example of vacation game sorting above games where the clock is active.

**Comment by dexonsmith** [comment]
The [sorting logic for clocks in GameList.applyCurrentSort](https://github.com/online-go/online-go.com/blob/3d6593ad1daf12808856f5cee02346b306d9d639/src/components/GameList/GameList.tsx#L85) is straightforward and doesn't directly consider paused games. The logic is:

1. is it the player's turn?
2. when does the clock expire? (`clock.expiration`)
3. what is the game ID?

I tried to track down how `clock.expiration` is set for paused games and couldn't find it (I suspect it's server-side, and I don't have access to that), but I did discover that the data type appears to be `number` in [src/models/games.d.ts](https://github.com/online-go/online-go.com/blob/3d6593ad1daf12808856f5cee02346b306d9d639/src/models/games.d.ts#L126).

I suspect that accessing/comparing the `clock.expiration` for a paused game fires an exception, which falls back to an `==` result.

If so, this would throw off the entire sort, since the comparison fails to follow strict-weak-ordering.

Consider the list of expiration times:
- 1
- 99
- throws

The pair-wise comparisons are:
- 1 < 99
- 1 == throws (!)
- 99 == throws (!)

With such a comparison function, the following are all "valid" results of the sort:
- 1, 99, throws
- throws, 1, 99
- 1, throws, 99
- 99, throws, 1 (?! because 1d == throws and throws == 1h)

**Comment by dexonsmith** [comment]
> I suspect that accessing/comparing the `clock.expiration` for a paused game fires an exception, which falls back to an `==` result.

Or, perhaps that what used to happen?

Playing with game lists on beta.online-go.com, it looks to me like paused games are consistently at the top of the list (or the bottom when in reverse sort). This suggests that `clock.expiration` is 0 or negative, not something that throws. I'll play around a bit more.

**Comment by dexonsmith** [comment]
Aha. I added some extra output to Clock.tsx:
```
		<div>since={goban.last_clock.paused_since}</div>
		<div>expiration={goban.last_clock.expiration}</div>
```
It looks like when a game is paused, `last_clock.expiration` is set to the time that the game was paused (equal to `paused_since`). This is why paused games are at the top of the list: their expiration time is in the past.

**Comment by dexonsmith** [comment]
I see a few ways to fix this.

1. Keep relying entirely on the AdHocClock. Sniff out whether the game is paused by looking at `expiration` and `paused_since`. If `paused_since` is set, that means the game was *ever* paused, since it's never unset. So, check if they're set and equal, and if so, consider the game "paused" and sort it after "unpaused" games.
2. Check the JGOFClock to figure out if the game is paused.
3. Same as (2), plus switch sorting logic over to JGOFClock (dropping this use of AdHocClock).

The JGOFClock option(s) seems cleaner. But I'm not sure if/when this JSON fallback is needed:
```
                        const a_clock =
                            a.goban && a.goban.last_clock ? a.goban.last_clock : a.json.clock;
```
and the JSON fallback relies on AdHocClock.

@anoek, any thoughts?

**Comment by anoek** [comment]
Yeah the pause system is kind of ugly. I reckon we need a method added to easily check and see if a game is paused or not. Here's how we do it in GobanCore:

https://github.com/online-go/goban/blob/main/src/GobanCore.ts#L3260-L3264

along with the definitions of those two functions later in that file:

https://github.com/online-go/goban/blob/main/src/GobanCore.ts#L4005-L4049
https://github.com/online-go/goban/blob/main/src/GobanCore.ts#L4125-L4130

**Comment by dexonsmith** [comment]
I think these are the options for fixing (but maybe I'm missing something):
- Server change required: Add `AdHocPauseControl` to the game list json so the initial sort knows if games are paused. (If we do this, I suggest also adding a `JGOFTimeControl`.)
- Pre-load all the `game.goban` fields before the initial sort. This seems potentially expensive though?
- Turn on the glitchy fix I mention above.
