### ISSUE TITLE
Faulty rank in play listing

### ISSUE THREAD

**Issue by fiddur** [online-go/online-go.com#47]
### Summary

In list of games waiting to start on `/play`, the rank inside `[]` efter a players name is faulty.

### Environment

 * Operating system: Debian Stretch
 * Browser:  Firefox
 * Browser Version: 45.7.0

### Steps To Reproduce:

1. Go to https://online-go.com/play
2. See the list of games, with players and ranks.
3. Click on player and bring up their profile page.
4. ...some of them have a very different rank than displayed.

### Additional Information:

![screenshot_20170228_145344](https://cloud.githubusercontent.com/assets/148166/23407850/2bacc0ec-fdc6-11e6-9cde-0d3ba6dbe40c.png)

![screenshot_20170228_145732](https://cloud.githubusercontent.com/assets/148166/23407891/3ebdbe16-fdc6-11e6-8d9d-6d155397ea3d.png)

**Comment by anoek** [comment]
In this case the users rank was adjusted to 5k after the challenge was created, so this isn't a major systemic problem (obviously optimally that adjustment would be reflected within open challenges, but it's a non trivial amount of work for a somewhat rare problem).

I'm going to close as 'wont fix' because in the not too distant future ranking system updates and auto-match will likely obviate this issue anyways.
