### ISSUE TITLE
Sort by time is having some serious issues rn

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#487]
### Summary

sort games by time remaining doesn't.

### Environment

 * Operating system: Windows 10
 * Browser: Google Chrome
 * Browser Version:

### Steps To Reproduce:

1. Go to any profile page or your own overview
2. Click sort by time remaining
3. See that the order seems to be random

### Additional Information:

https://forums.online-go.com/t/sort-by-time-remaining-is-having-some-serious-issues-rn/14291

![image](https://user-images.githubusercontent.com/28991649/31580998-e4b014de-b1aa-11e7-8b64-e6a8ba0d7b66.png)

**Comment by GreenAsJade** [comment]
Is it still doing this for you?

I can't find a broken example...

**Comment by BHydden** [comment]
No... Whatever was causing this random bug appears to be resolved now...

**Comment by Spoekenkieker** [comment]
Still doing it for me, see attached screenshot (showing just the first three out of ~20 games). And it’s only the first game that’s out of line, all the other ones are in correct order.

![image](https://user-images.githubusercontent.com/7978735/31819090-55e455f4-b59b-11e7-8347-8a292ae15511.png)

**Comment by BHydden** [comment]
Will reopen due to above comment

**Comment by GreenAsJade** [comment]
I wonder if it is significant that the first one of these, which is the one that is out of order, is also under vacation?

It would be interesting to have an example of the "bug" where the game out of place isn't special in that way...  

... it would also be interesting to see if that game gets back in place when vacation is removed.

Maybe "vacation" is sorting to the top, because it doesn't have a due or something like that.

**Comment by Spoekenkieker** [comment]
GAJ, you seem to have something there … this time it’s not vacation but weekend (see screenshot below).

Also, in the cases of vacation/weekend it should rather sort behind, not in fron, because the time’s stopped, no?

![image](https://user-images.githubusercontent.com/7978735/31855196-e32bf0f6-b6a5-11e7-9f42-7d7e524230a4.png)

**Comment by GreenAsJade** [comment]
Yeah totally.

**Comment by GreenAsJade** [comment]
In which case in some ways this become an enhancement rather than a bug: they are sorting "OK", we'd just like them to sort differently.

**Comment by GreenAsJade** [comment]
I think this bug could be closed, and another enhancement request raised for paused games to sort as "oldest" not "newest"

**Comment by BHydden** [comment]
OP resolved, new issue created as above.
