### ISSUE TITLE
Black/white player names always have '?' ranks in game info modal

### ISSUE THREAD

**Issue by anoek** [online-go/online-go.com#489]
### Summary

Black/white player fields in the game info modal appear with question mark ranks regardless of actual rank information.

### Steps To Reproduce:

1. Go a game
2. Click on the 'i' info button on the right to open the game info modal
2. Notice both black and white players have a question mark for their rank

### Additional Information:

![image](https://user-images.githubusercontent.com/168460/31717535-535bad90-b3da-11e7-949b-03eb4f1a647d.png)

**Comment by GreenAsJade** [comment]
@anoek The thing that stands out about this is that the GameInfoModal instantiates Player with DisableCacheUpdate set true.

Experimentally, if you set that to false instead, this bug goes away.

I think that a person who knows what's going on with caching would be best placed to determine if this is a wise solution, but it appears to be _a_ solution.

GaJ

**Comment by GreenAsJade** [comment]
OK - so there are Deep and Mysterious things happening.

As far as I can see, GameInfoModal grabs it's snapshot of the user at construction time, and at this time for some reason the rating of the user is not yet on the user object.

At this time, the user looks like this:

{username: "TestGaj", professional: false, egf: 0, rank: 0, id: 646}

and the resulting rating from getUserRating is

{professional: false, unset: true, rating: 1500, deviation: 350, volatility: 0.06, …}

The actual mechanics that follow are that we get "?" because the deviation is too high, but really I think it's say "whoa, I don't have the rating info yet"

In contrast, by the time the Game screen is rendered, the user that is passed to the Player on that screen is 

{username: "TestGaj", ratings: {…}, ranking: 0, country: "TestGaj", professional: false, …}

... you can see it has ratings.

I think it boils down to the fact that the GameInfoModal is created very early in the lifecycle of the Game that contains it, before the user info has been set up properly, so it's rendering of the Players is not right.

Wheras the Player components that appear on the Game page itself are created during the render of the Game page, each time it renders, so by the time it's done they have the right info.

IE caching the user info at construction is too soon :)

**Comment by GreenAsJade** [comment]
... since someone obviously put this together with some performance considerations in mind, I think I'll leave it there, because those would be fiendish to figure out :)
