### ISSUE TITLE
CSS is not valid (not mentioning the vendor extensions)

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#534]
### Summary

Many errors in the validator ... And, I could see typos amongst them.

### Environment

any

### Steps To Reproduce:

n/a

### Additional Information:

https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fonline-go.com%2Fchat&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en#errors

**Comment by anoek** [comment]
Meh.. CSS is gross.

A bunch of those errors are coming from 3rd party libs, and a lot of the other errors stem from the fact that we have some auto-prefixer that lets us take advantage of some css4 features (ie, `user-select` being one example) which is widly supported but dropping in the `user-select` property is not technically valid css3. However, we don't really care because browsers just skip over properties they don't know how to deal with, so totally benign and helps with preparing for the future.

**Comment by arnaudgo** [comment]
Hello,

Yes @anoek I know very well these points actually and perhaps I have opened the issue maybe too quickly.
What is sure is that my formulation was incorrect.
Indeed, there are warnings and error that are expected as the vendor properties, others than are not worth to care about neither.
So the non-validity is not the issue I wanted to raise, but I could see some typos like boder-color rather than border-color. And I also suspect other w/e to be that kind of inattention mistakes. 
the consequence is those properties might be ignored by ALL browsers which is probably not what you had expected.
Of course, it's a very low percentage and I didn't make the hard work to eliminate ... let's call them false-positives.
They are not false-positives, it's the way the validator works, they are not bugs. You see what I mean anyway.
So, you can take the opportunity to correct the very minor mistakes you could spot with a short second glance.
Well, if you deem it necessary...

Arnaud

**Comment by anoek** [comment]
`boder` typo's is funny and certainly worth fixing, there's a lot of stuff to parse in there, i'll skim through and see if i can find some more before closing again.
