### ISSUE TITLE
Victors should be able to self anull games when they win by timeout

### ISSUE THREAD

**Issue by TableCarpet** [online-go/online-go.com#538]
When I win by timeout my rank increasing. Even if I far behind in score. 
I need option to cancel my rank increase if I win by timeout.

10 seconds / move is enough to win a lot of games purely by timeout because most people are slow. So if you play blitz and don't timeout, your rank inevitably higher than real. You can't play blitz and not become airbagger.

I recently discovered that if you play strange strategy, a lot of people leave even with 1 minute / move. So my rank becoming too high even without blitz.

Option to cancel rank increase if I think I lost will solve this problem. Its impossible to use such solution to become sandbagger because its only available in win by timeout.

**Comment by GreenAsJade** [comment]
It seems to me that winning by timeout is a fine strategy for blitz, and your rank is not wrong, it's just correctly showing that you win a lot of blitz games because you make your opponents time out.

Playing strangely to make people leave is a strategy just like any other.

I don't think any of this means your rank is wrong, it just means blitz is a strange format.

Arguably we should have separate ranks for blitz, live and correspondence, so people don't mistakenly think you are highly ranked at less timeouty formats.

There is a workaround for this, which is to run separate accounts for playing each format.

I have a separate account for playing live and correspondence, because I am nowhere near as good at live.

**Comment by TableCarpet** [comment]
There are different meanings of word "rank". You can be 7k because you can create board position after which AlphaGo on your side can win other AlphaGo. Or you can be 7k because people leave/timeout.
In current system you don't have choice. I talk about ability to choose meaning for your own rank.

**Comment by GreenAsJade** [comment]
Yeah I guess that makes some sense.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
