### ISSUE TITLE
Review Tool: Quick Jump to Boardstate

### ISSUE THREAD

**Issue by Tr1bute** [online-go/online-go.com#563]
In the current state of the **Review** mode, players are able to **Shift+Click** on a stone to go back to the board state when that stone was played. It would be really useful if you could also **Shift+Click** on an empty intersection to skip **forward** to the board position where a move on that spot was played.

My teacher uses this feature to a great degree, and I can't imagine how long a review would take if this wasn't possible for him. I truly believe that this will improve the teaching community on OGS a lot, if this feature were to be implemented.

**Comment by stephancurran** [comment]
I'm working on a fix for this, but I need some advice on the exact behaviour required. At the moment, shift-clicking a point searches to the end of the current branch and it's sub-branches for the move, and then works backwards to the trunk (looking for a "nearby" match), and checks remaining branches of that trunk move before checking the trunk itself. It doesn't check any other branch moves because there could be any number of matches and no way of knowing which one the the user might require.

Does this seem like suitable behaviour, or should I use a different tack?

**Comment by Tr1bute** [comment]
Great! This sounds right to me.

After playing around a bit on the CGOBAN tool, this is what I found.
In addition to searching the remaining branches of the current trunk, it will prioritize the current branch, then the parent branch, in-case there are moves that overlap each-other.

For example.

1. I'm explaining something in the trunk branch, making a new sub-branch.
2. I remove a stone that was previously played way before, and make up a new sequence that includes this move, but later.
2. (Currently in the sub-branch) I want to move back(or forward) to this place on this branch, so I shift-click on the stone, or the empty intersection where it is.
3. The system should now take me to the move on the sub-branch I'm currently in.
4. In the case where the system does not find a match in the sub-branch for that particular move, there seems to be three different behaviors on CGOBAN.
4.1 If the user clicked on a stone. (Trying to go backwards) It will take the user back to that move, and to the branch where that move was played, still prioritizing the current sub-branch.
4.2 If the user clicked on an empty intersection. (Trying to go forwards) It will not find the move if it is only found in the parent of the current branch, and instead requires that the user switches branches manually first.
4.3 If the user is currently in trunk, and clicked on an empty intersection, and the system did not find the move in the trunk branch, it will search the sub-branches of trunk for that move. If it was found, it will move the user to that board position and branch.

Essentially. 
Going **forward** can take you down to children of the branch, but not up to the parent.
Going **backward** can take you up to the parent, only if the move doesn't exist in the current sub-branch.

Cgoban also has the concept of the current "Active branch", which it keeps track of even if the user goes all the way back to the root node. To me, this seems to be how they have chosen to prevent this system from taking you to another trunk branch. Of course, that's a little out of topic here. :)

**Comment by stephancurran** [comment]
OGS doesn't seem to maintain the active branch like that (although something is partially implemented from what I can tell...perhaps @anoek can confirm that?); only the moves up to the current one (blue square) are highlighted.

Here is the search sequence from a trunk move. First the current move is checked, followed by its branches. It then comes back and checks the entire trunk beginning at move 1.
![ogstreetrunk_labeled](https://user-images.githubusercontent.com/494175/36877800-4d8235b4-1dbc-11e8-947c-1d790f66abad.png)

And this shows the sequence from a branch move. It checks all sub-branches before working backwards to the trunk node, and then checking the trunk itself. Branches of other trunk nodes are ignored.
![ogstree_labeled](https://user-images.githubusercontent.com/494175/36877801-4da73e04-1dbc-11e8-8bfa-4c5d51336dd3.png)

In each case, the trunk node is checked twice because skipping it would require an if statement on every node along the way, which is probably going to be slower than just checking it again, and wouldn't change the outcome.

If there's a more sensible sequence for walking the game tree, I'd be happy to implement it.

**Comment by anoek** [comment]
Completed in #588, thanks @stephancurran !
