### ISSUE TITLE
Game link in rating graph is barely viewable against background

### ISSUE THREAD

**Issue by ck244** [online-go/online-go.com#57]
### Summary

In the ratings graph under a user's profile, the game link is barely viewable. This should be changed to a lighter color to contrast the gray box; currently it's a dark gray which makes it barely visable. I would make a pull request, but I don't have my environment setup just yet. If you can point me to the area where this code exists, I can take a crack at updating the style there. Thanks.

### Environment

 * Operating system: Win 8
 * Browser: Chrome
 * Browser Version: 55.0

### Steps To Reproduce:
In the user's profile, hover over a point in the ratings graph where the rating changed due to a game result. The link is contained in the box which pops up under the cursor.

Example screenshot:
![image](https://cloud.githubusercontent.com/assets/20911321/23474072/5919fae4-fe67-11e6-9c94-917cd4d036cb.png)

**Comment by anoek** [comment]
The code you're looking for is here: https://github.com/online-go/online-go.com/blob/devel/src/views/User/User.tsx#L573-L578 and probably the corresponding sytlesheet stuff here: https://github.com/online-go/online-go.com/blob/devel/src/views/User/User.styl

**Comment by anoek** [comment]
And yeah, that sure is ugly right now :) PR would be appreciated :)

**Comment by ck244** [comment]
Hmm, it looks like after I run 'npm run dev' (on Ubuntu), I can navigate to http://(internal host IP):8080 but I get a blank page with the title "OGS", and nothing else. Each time I try to reload the page it just spits out "GET /" to the terminal, but nothing shows up on the screen. Hoping I'm not missing anything in my setup, all I did was make sure node v6.10 was installed from repositories.

**Comment by anoek** [comment]
Any error messages on the JavaScript console? Are and build errors on the
terminal?

On Mar 2, 2017 02:51, "Chris Kang" <notifications@github.com> wrote:

Hmm, it looks like after I run 'npm run dev' (on Ubuntu), I can navigate to
http://(internal host IP):8080 but I get a blank page with the title "OGS",
and nothing else. Each time I try to reload the page it just spits out "GET
/" to the terminal, but nothing shows up on the screen. Hoping I'm not
missing anything in my setup, all I did was make sure node v6.10 was
installed from repositories.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/online-go/online-go.com/issues/57#issuecomment-283581465>,
or mute the thread

**Comment by ck244** [comment]
I deleted my earlier comment, got it to work on my other machine!
