### ISSUE TITLE
Introduce humble rank for display/matchmaking 

### ISSUE THREAD

**Issue by lemurek** [online-go/online-go.com#570]
### Summary

Following thread discusses harmfulness of introductory 13k base rank. Whether the current solution is really harmful and prevents new comers from staying around on the server is beyond the scope of this issue. 

https://forums.online-go.com/t/i-think-the-13k-default-rank-is-doing-harm/13480

One of the proposed solutions suggests introduction of 'humble rank' concept, which corresponds to lower confidence boundary of glicko-2 rating (i.e. rating - deviation) for display / matchmaking purposes. More details of the proposition can be found here:

https://forums.online-go.com/t/i-think-the-13k-default-rank-is-doing-harm/13480/91

### Environment

 * Operating system: any
 * Browser: any
 * Browser Version: any

**Comment by lemurek** [comment]
I've opened the issue as a placeholder for the PoC work I did. It's an interesting idea, but personally I'm not too attached to this particular approach. We need @anoek to jump in with his perspective on the whole 13k issue before we move anywhere.

**Comment by anoek** [comment]
My hunch is resolving this will have very little UI work to do, I need to sit down with the match data for the past year and run some numbers.

**Comment by GreenAsJade** [comment]
Cool!   Note that an extension to the proposal in the linked post was to add an offset to the "raw humble rank", to counter the natural uncertainty.   And thus most people's rank would not be changed significantly.

This offset could either be fixed at approximately the "average" uncertainty (I'd say 2.0 would be just fine just from what I've seen) or calculated from the data somehow.   I don't think actual average is the right number, as that is affected by the new players' high uncertainty.   Maybe mode or some such?   It probably doesn't have to be that scientific, since it is uniform and is just to make people feel OK.

**Comment by GreenAsJade** [comment]
This topic came up again today, with people trying to avoid matchups with [?] players.

https://forums.online-go.com/t/how-to-block-from-accepting-game-request/18145

Where does it sit in "dev priority/likelihood"?
