### ISSUE TITLE
Game in progress does not appear in my home/profile page

### ISSUE THREAD

**Issue by rshouker** [online-go/online-go.com#584]
### Summary

Game in progress does not appear in my home/profile page, neither on my opponent’s profile page.

### Steps To Reproduce:

1. visit https://online-go.com/game/11775278
2. From there view either the players' profile.
3. See that the game does not show there.

### Additional Information:

Also it doesn’t have an icon with a link to the ladder. I don’t remember which ladder the challenge was made.
Also our avatar and ranks doesn’t show.
The game may have been part of the 19x19 ladder of the group “Sandbox” which seem to have disappeared.

**Comment by anoek** [comment]
Bleh, this is a "ghost game". This has been a bug that we've been hunting for awhile.. what happens is that a game is started on the game servers but isn't registered in the main database. The entire game can be played out, and the history will even be recorded, but it wont count for anything. Because it's not in the main database, it wont count towards your rank, wont be on your game page, won't count as a ladder game, and won't show up in your game history.

If you'd like I can tie the game or someone can just resign. Or you can play it out, it's effectively just an unranked unregistered game at this point.

Sorry for the inconvenience.. it's been a pain in our side for awhile now.

**Comment by rshouker** [comment]
I don't think it started out that way. I only notice a discrepancy between the game count of the chrome extension, and that of the site itself (black circle,) a few days ago, and the game has started longer than that.
Perhaps you can reproduce this case by creating a group, have 2 players join its ladder, make a ladder challenge, then delete the group (If there is such an operation at all, otherwise the "Sandbox" group disappearance is a bug by itself.)

**Comment by anoek** [comment]
Oh interesting, I'll try that out and see if i can reproduce. Thanks for the information!
