### ISSUE TITLE
Ability to download the game record in an animated gif/png

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#595]
### Summary

It would be fun and nice to be able to download the game record in an animated png/gif.

### Environment

 any

### Steps To Reproduce:

n/a

### Additional Information:

Ask if needed.

Arnaud

**Comment by apetresc** [comment]
Yeah, chess.com has this feature and it's really exploded the amount of social media sharing that happens there. I think this would result in a lot of eyeballs for OGS. Good idea, @arnaudgo.

**Comment by dragon96** [comment]
@anoek I'm looking into taking this feature on. Would you be able to point me to the current image stuff you mentioned?

**Comment by anoek** [comment]
It's on the backend unfortunately :(

**Comment by rileylark** [comment]
I think this is a neat idea and with some clarification could be made into a fun challenge that someone could chunk off and complete!

In the spirit of clarifying, I have a few questions:

### Main Purpose

- Would the main goal be social media sharing? 
- If so, is there a current known best channel? Like should it be optimized for tweeting, or maybe export straight to youtube? Or maybe the community is using slack or a message board most?
- Are there any examples where people use animated games at a fixed speed already?
- Could the chess.com model be copied directly for OGS or is there something that would need to change to support go or the OGS user model?

### Brainstorming ideas

- I'm picturing adding annotations to make a GIF easier to comprehend as it flits by at a quick pace. Would it be cool to overlay the scoring estimator territory shading so it would be more obvious to beginners what was happening?

- Highlight reels - since some games are so long, maybe we'd want to find highlights like big captures or big strategic swings and just render the +/- 10 moves around them?
