### ISSUE TITLE
Showing handicap info in game history and mini board

### ISSUE THREAD

**Issue by lemonsqueeze** [online-go/online-go.com#626]
Hi,
One feature i'm missing at the moment is easy access to handicap info in players' game history and the mini board used to display active games. I think it'd be great to have it displayed there instead of having to open each game to find out if it is even game, handicap ...

How about something like this: (or on the side)
![foo2](https://user-images.githubusercontent.com/2463904/38448797-9872dfe4-3a07-11e8-869d-84665759f0e4.png)

![foo](https://user-images.githubusercontent.com/2463904/38448813-b6eeeeb8-3a07-11e8-84e8-fbf8294c01bb.png)

**Special bonus:** The main "Games" tab list could use something like this too, but i have to admit i don't use it very much, it's a bit psychedelic with all the clocks ticking =)

**Comment by anoek** [comment]
I'm open to something like this, more so on the game history table than on the mini boards, but I'd be open to having it on the miniboards too if it can be done prettily. I think I would avoid having the h2 right before the clock as I think that adds some visual clutter to an important thing, but maybe on the side similar to how the points are displayed or something?

**Comment by lemonsqueeze** [comment]
Yes, i like on the side too.
If we have to choose, for miniboards i'd rather have handicap info than points actually, better at giving a quick idea what the game is about.

**Comment by anoek** [comment]
I think you'd get a lot of push back for removing the points, that was asked for pretty passionately back when we didn't have it :) I don't think one would have to choose though. I do question how sought after the feature is though, to me the handicap information is encapsulated in the game state, usually you can either immediately tell because the game is early on, or it's kind of a moot point because you can see very clearly how the game is going with a quick glance at the board and possibly looking a the points to get a feel for captures, komi, and handicap adjustments. But if there's some interest from folks and it doesn't cause clutter problems for other folks, then I have no objections.

**Comment by lemonsqueeze** [comment]
Also for game history it'd be useful to have game type (Ranked / Free), would make it a lot easier to spot sandbaggers who only play free games.

**Comment by anoek** [comment]
Closing due to lack of progress on this

**Comment by lemonsqueeze** [comment]
Note for future contributors: don't waste your time on this project.
