### ISSUE TITLE
Live tournament starts two games simultaneously

### ISSUE THREAD

**Issue by 994PhiJ** [online-go/online-go.com#674]
### Summary

In the second round of today's Live 19×19 Swiss Tournament, everybody started two games (but only one of them was on the tournament listings).  

This is probably why some people have an extra point (e.g. in the tournament linked below the list says Guru Pathik has 5 points but only won 4 games - presumably they won their invisible game too).

### Environment

 * Operating system: Linux
 * Browser: Firefox
 * Browser Version: 52.8.0

### Steps To Reproduce:

Get 6 people to join a live 19×19 Swiss Tournament, and hope the problem recurs.

### Additional Information:

Tournament: https://online-go.com/tournament/39054

My simultaneous games are these two:
https://online-go.com/game/13603310
https://online-go.com/game/13603311

It looks like this has happened before:
https://forums.online-go.com/t/bug-parallel-live-tournament-games/11521
https://forums.online-go.com/t/tournament-bug-2016-03-17/6923
https://forums.online-go.com/t/tournament-assigned-two-games-at-once-to-each-player/9052

**Comment by Purble1** [comment]
### Further example:
Same thing has just happened in an ongoing correspondence tournament I'm in: https://online-go.com/tournament/25276

My two games:
https://online-go.com/game/13695470
https://online-go.com/game/13695462

**Comment by theshteves** [comment]
Hey @anoek,

I was hoping to scratch this itch and dig into the source myself.  I'm very new to React's state & lifecycles but they didn't trouble me until I got stuck for an hour figuring out where the heck the trophies state info is coming from?
https://github.com/online-go/online-go.com/blob/devel/src/views/User/User.tsx#L815

Multiple grep's across the codebase have come up short (is there some... i don't know... Typescript property setting feature that I'm not aware of?)  I know that the problem is likely much earlier in the tournament execution and I have a couple different approaches to try but, in the mean time, I'd _really_ appreciate your input on where that state is set.

**Comment by theshteves** [comment]
I noticed the Django REST framework which I've always been a big fan of.  Any chance I could take a crack at it with my Python background?  I haven't seen that python/Django on this team's repo but I'd love to contribute.

**Comment by anoek** [comment]
We'd like to open up the backend at some point, but it's quite the beast to get running at this point, and there's some sensitive stuff still in the repo, so we can't do it right now. We'll make an announcement if/when we do though :)

**Comment by koshogs** [comment]
## Further Example With an Observation (clue?) to the Problem:

Incident occurred here: [tournament/42799](https://online-go.com/tournament/42799)

In round 3 these two games were erroneous, do not appear on the tournament page and caused simultaneous games for three of the participants(thankfully not me).: [game15286976](https://online-go.com/game/view/15286976) & [game15286977](https://online-go.com/game/view/15286977)
The first one in particular should not have occurred in this double-elimination because one of the players was undefeated while the other had progressed to the bottom tree.  Numerically this game was created first in that round.

Another oddity:  In the preceding round 2, there were no simultaneous games BUT it looks like the system may have tried to create them with these 'non-games' immediately following those of the second round:  [game15286843](https://online-go.com/game/view/15286843) & [game15286844](https://online-go.com/game/view/15286844).

Hope that helps.

**Comment by yewang** [comment]
Further instances reported in this forum thread:
https://forums.online-go.com/t/doubled-games-in-tournament/24602
