### ISSUE TITLE
Indicate that no emails will be sent to the configured email address when address has been blocked

### ISSUE THREAD

**Issue by nickeubank** [online-go/online-go.com#685]
### Summary

Not getting email notifications. May be resurrection of #420 (not clear that ever got fixed), where emails stop being send if too many bounces. 

I'm wondering, though, if this may be triggered by vacation auto-replies. Is that plausible?

**Comment by anoek** [comment]
#420 wasn't a bug, that's the way the system is designed. If an email address is unable to accept emails, we stop sending emails to it. We actually have to do this to stay in compliance with Amazon (who we use to send emails), otherwise they think we are spammers and stop sending emails on our behalf :) I've cleared the flag for you again though, so you should be all set now.

**Comment by nickeubank** [comment]
@anoek So I think it's a "bug" in the sense that there's no way for users to know what's happening or to reset things (without a github issue). 

The problem is that this is being set off by normal behavior (in this case, vacation auto-responses). My OGS email is my primary (professional) email and has not been offline for years, so I'm 99% sure what's happening is that when I set up an auto-reply for the month around when my daughter was born, those auto-replies turned off OGS. Seems like we need a setting on the profile page to alert users when that's happened and allow them to remove the flag themselves.

**Comment by anoek** [comment]
Yeah fair enough, I'll keep it open to track that feature

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
