### ISSUE TITLE
Pauses in correspondence tourneys can make trouble

### ISSUE THREAD

**Issue by Adam314159** [online-go/online-go.com#694]
### Summary
An unnoticed pause in a corr. tourney can drag it out a lot.
Maybe disallow pauses in those, or make them optional upon creation?

### Environment
irrelevant

### Additional Information:

https://forums.online-go.com/t/dont-allow-pause-in-correspondence-tournaments-and-ladder-games/18474

https://forums.online-go.com/t/my-opponent-paused-our-game-what-to-do/15010/10

**Comment by koshogs** [comment]
Github gives me a headache but here I am. Thankyou for opening the batting on this Adam.

I would add that this issue is potentially an 'internal bleeding' issue in that many users may have a diminished OGS-tournament experience without ever knowing why (and so not complain).

Consideration should also be given to ladder games which are effectively never-ending tournaments.

As Adam says, the two solutions appear to be disabling pause for all correspondence tournaments (and ladders) or making it an element of tournament creation.

The former is probably easier to implement but the latter would be ideal, with 'no-pause' as the default.  

I wanted to add that if it is added as a tournament creation option then it might be a perfect opportunity to also have a 'vacation allowed/disallowed' setting in tournament creation, though for that I would strongly suggest 'Vacation allowed' as the default.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
