### ISSUE TITLE
Show all my ladders on ladders-tab

### ISSUE THREAD

**Issue by kobakitty** [online-go/online-go.com#703]
online-go.com/ladders currently only shows the sitewide ladders, but could it also present the group ladders where i am in?

**Comment by BHydden** [comment]
I took a stab at implementing this and was quickly overwhelmed! 🤣 

I thought I could borrow [the code](https://github.com/online-go/online-go.com/blob/devel/src/views/User/User.tsx#L982-L991) from [the profile page](https://github.com/online-go/online-go.com/blob/devel/src/views/User/User.tsx) that lists all your current ladders and just convert it to a card and call it done...
```
<h4>{_("Ladders")}</h4>
{(this.state.ladders.length > 0) && <div >
    <dl className="activity-dl">
        {this.state.ladders.map((ladder, idx) => (
        <dd key={idx}>
            #{ladder.rank} <a href={`/ladder/${ladder.id}`}>{ladder.name}</a>
        </dd>
        ))}
    </dl>
</div>}
```

...but it turns out both files use [the same line of code](https://github.com/online-go/online-go.com/blob/devel/src/views/LadderList/LadderList.tsx#L68-L75) to populate their list, meaning they're coming from different sources. I know the [/ladders page](https://github.com/online-go/online-go.com/blob/devel/src/views/LadderList/LadderList.tsx) gets its list from [LadderComponent](https://github.com/online-go/online-go.com/blob/devel/src/components/LadderComponent/LadderComponent.tsx) but for the life of me, I can't figure out where [the profile page](https://github.com/online-go/online-go.com/blob/devel/src/views/User/User.tsx) imports `this.state.ladders` from! 😖 

Sorry for my ignorance! Might I trouble @anoek , @flovo or @GreenAsJade for a point in the right direction? 😍

**Comment by flovo** [comment]
According to the Firefox Network Monitor (Ctrl+Shift+E) it's `https://online-go.com/api/v1/me/ladders`.

It's pulled in https://github.com/online-go/online-go.com/blob/d0d14dd2d1a4c37867f64dc96a80f135d04e8073/src/lib/cached.ts#L43
And the code using it to fill the Overview page: https://github.com/online-go/online-go.com/blob/d0d14dd2d1a4c37867f64dc96a80f135d04e8073/src/views/Overview/Overview.tsx#L296-L331

The Profile page uses `https://online-go.com/api/v1/players/$pid/full` to get the active ladders, since you can have a look at every user's profile page and want to see in which ladders they are participating, not in which you are.

**Comment by BHydden** [comment]
> According to the Firefox Network Monitor (Ctrl+Shift+E)

Awesome! I'll have to remember that one!



> the Overview page

D'oh! Of course! I can't believe I forgot the overview page 😞  rookie error 😛  Thanks heaps!!

Hopefully, all that will be enough for me to sort out something decent looking 😄  Have a look at it tomorrow morning most likely 😄

**Comment by kobakitty** [comment]
@BHydden did you ever had the time to take another look at it? Is this "under construction"?

**Comment by BHydden** [comment]
Not currently @kobakitty my dev environment is so out of date at this point it'd probably almost be faster to scrap it and start again 😅 if you're interested in taking a stab at it be my guest

**Comment by BHydden** [comment]
I still think this would be a neat update but also don't have time for implementing it myself.

Any chance I can inspire @benjaminpjones to adopt it? 😁

**Comment by benjaminpjones** [comment]
It does seem like a neat idea! Maybe we just re-open it as a [good first issue](https://github.com/online-go/online-go.com/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)?

**Comment by BHydden** [comment]
Sounds good to me. It shouldn't be too hard with this discussion thread to follow.

**Comment by benjaminpjones** [comment]
https://github.com/online-go/online-go.com/commit/4a1a802da5d8d57aa921c8f41aaddcbb8e460939
