### ISSUE TITLE
In some circumstances, submit button can pick up wrong stone placement

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#732]
### Summary

A user reported that, on a mobile:

[9:39] stevenjackson121: the problem is that the submit button begins making the new page load before I've raised my finger off the screen, and after the screen moves, my finger is interpreted as selecting a different intersection). You (or the developers) can likely reproduce this effect yourself by exaggerating the length of your press after scrolling down to hit "submit"

### Environment

 * Operating system: unk
 * Browser:  unk
 * Browser Version: unk

### Steps To Reproduce:

1. Have multiple correspondence games with turns waiting to be played
2. Be in "move to next game upon submit" mode
3. Be in submit-button mode
4. Access a correspondence game in a browser on a phone
5. Click a move on a correspondence turn
6. Hold down "Submit" button until the page starts loading the next game
7. Release

PS: don't do this on a game that you care about.

(note: I have not reproduced this, just reporting as told to me)

**Comment by stevenjackson121** [comment]
To clarify step 4: 
Access a correspondence game in a browser on a phone where the submit button is displayed below the board, off the bottom of the screen.

And between steps 5 and 6:
5.5) Scroll down to bring the submit button into view.

On my device, the submit button is _usually_ visible directly below the board with no scrolling required (and thus the problem never occurs). However if there is at least one long username, and byoyomi periods are used, then the information display at the top takes up 3 lines, e.g.:

```
long_username
3 days 4 hours
+ 5 x 1 day
```
instead of
```
long_username 
25 hours
```
or
```
short_name 25 hours
```


I believe the time controls/name length factor is why this happened to me twice in one game, when it hasn't occurred at all in any of my other games.
