### ISSUE TITLE
Games occasionally being auto-scored incorrectly

### ISSUE THREAD

**Issue by AdamT213** [online-go/online-go.com#760]
### Summary

In all the games I have played, I have only observed this issue once. The first autoscore generated seemed correct, but it quickly switched to a much higher score differential, which was ultimately the one saved. It did not change who had won, but did greatly change the score, which, if I understand the ranking algorithm correctly, may affect rank.

### Environment

 * Operating system: android (galaxy S8)
 * Browser: Samsung Internet

### Steps To Reproduce:
May be difficult to reproduce, but I included a screenshot to show the instance when it happened.

### Additional Information:

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*
![2019-04-08](https://user-images.githubusercontent.com/31555893/55737412-000b6480-59da-11e9-8126-2e978d47fe36.png)

**Comment by AdamT213** [comment]
If this is indeed a bug and not a designed behavior, I would be happy to look into it. I want to get more involved with this repository.

**Comment by GreenAsJade** [comment]
The game you have pictured appears to be scored correctly.   Could you clarify what the apparent problem with it is?

In general, the auto-score is only intended as an initial estimate of the score, to ease the scoring phase:

https://github.com/online-go/online-go.com/wiki/The-game-view-and-playing-games#scoring-the-stone-removal-phase

It is an estimate, and can come up with different answers each time because in some situations it has to "guess" what might happen.

It is known to have trouble with some situations, though the pictured game is not one of those.

It would be awesome if someone could fix those, because it _is_ used in the actual scoring of games vs bots.   

It may also be worth nothing that only win/loss status affects rank, not the margin of the win.

**Comment by AdamT213** [comment]
Huh. Maybe my understanding of the game is flawed then (it certainly is), but I don't see why white's territory is considered dead. It seems to me that white could live in this case. Nonetheless, if the score doesn't affect rank, then I suppose it doesn't really matter anyway.

**Comment by GreenAsJade** [comment]
Oh, you're right, I completely misread the picture!

Let me think about that :)

**Comment by GreenAsJade** [comment]
OK - so I visited the game and pressed "estimate score" and it correctly handles it.

The picture above looks like what happens when one player incorrectly clicks the white stones dead.

That would explain your experience - you entered the scoring phase, saw the score you expected to see, then "out of the blue" your opponent clicked the board incorrectly selecting a wrong score.

This typically happens when either

1) the person is newish and they don't really understand

 https://github.com/online-go/online-go.com/wiki/The-game-view-and-playing-games#scoring-the-stone-removal-phase

or 

2) the other person is trying to cheat by tricking you into accepting a wrong score.

Since in this case the person "gave" the game to you, I assume that it was the former :)

**Comment by AdamT213** [comment]
Makes sense. All is well.

**Comment by GreenAsJade** [comment]
If you're looking for a worthy get-started on OGS client work project/task, here's one that just surfaced:   https://forums.online-go.com/t/quick-match-finder-ui-is-this-a-bug-suboptimal-fine-as-is/20992/2?u=greenasjade

**Comment by AdamT213** [comment]
Cool, thank you. I will work on that!
