### ISSUE TITLE
Win-loss bar graph gets clipped

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#810]
### Summary

The lower part of the win-loss bar graph gets clipped off. 

### Environment

 * Operating system: Linux / Android
 * Browser: Firefox
 * Browser Version: 67.0.1 (64-bit)

### Steps To Reproduce:

1. Go to Profile page https://online-go.com/user/view/449941
2. The lower part of the Win-loss bar graph is cropped off.

### Additional Information:

This is how it looks:
![image](https://user-images.githubusercontent.com/4864182/59212114-d1646280-8bb1-11e9-8754-b23a6f8517bc.png)

It should look like
![image](https://user-images.githubusercontent.com/4864182/59212181-02449780-8bb2-11e9-973a-1756a90df757.png)
I removed the clipPath to see the whole chart.
![Clippath](https://user-images.githubusercontent.com/4864182/59212325-5ea7b700-8bb2-11e9-92fc-260f594142d0.png)

**Comment by anoek** [comment]
@tcarette might have an idea?

**Comment by tcarette** [comment]
I'll check asap

**Comment by BHydden** [comment]
Am I the only one not seeing the difference? #precoffee

**Comment by tcarette** [comment]
lol. It is there.
I'm searching but I don't think it is related to the latest release. I could reproduce it with a previous version.
But I'm glad to look at it since I have the code open anyway :-)

**Comment by tcarette** [comment]
ok - shot in the dark fix here. Please somebody reviews my interpretation below and tell me if it sounds ok.
https://github.com/tcarette/online-go.com/tree/issue_810

The logic is the following: `outcomes_x` maps the game count domain on a range of y-values and heights. The bar chart height was parametrized with `win_loss_bars_height`, set at 65, but the range of `outcomes_x` was hardcoded to 60. So my guess is it should be set to `win_loss_bars_height` as in the commit.

Seems sound?

Because it still looks like it is a bit clipped. Actually, there is a bunch of things in this graph that seem to not align just right. But hopefully it is not too noticeable; I don't want to do a patch that is illogical "but works".

![image](https://user-images.githubusercontent.com/2481066/59230215-0639df00-8bdd-11e9-82cc-9e4d1b3cbe90.png)

**Comment by tcarette** [comment]
tbh, I don't know where this clipPath is coming from either... 😕

**Comment by flovo** [comment]
I think the lines creating the clipPath are, but I cannot check at the moment
https://github.com/online-go/online-go.com/blob/a936719f18231706e69af3fc656c9a77ab334686/src/components/RatingsChart/RatingsChart.tsx#L279-L284
https://github.com/online-go/online-go.com/blob/a936719f18231706e69af3fc656c9a77ab334686/src/components/RatingsChart/RatingsChart.tsx#L565-L566

**Comment by tcarette** [comment]
Ok, indeed.

I've increased the clipPath height to the svg height and it seems to work fine now

I might do a pull request if there is no reaction. Any suggestion for better testing?

Here is the branch that fixes. There is a few extra changes which make the spacings betters.
https://github.com/tcarette/online-go.com/tree/issue_810

**Comment by anoek** [comment]
Yeah sorry there's not a user with a lot of data there to do some better testing with on the beta server. You can however point the dev proxy to the main servers if you would like, then you can browse any number of established players to do some more testing. To this open up `Gulpfile.js` and change `beta.online-go.com` to `online-go.com` in the two places (one is the proxy setting, the other hacks in the url for the websocket).

**Comment by flovo** [comment]
Thank you. 
Now it works as expected.
:+1:
