### ISSUE TITLE
Use AI to determine lost games in Serial Timeout scenario

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#823]
As discussed and summarised here:

https://forums.online-go.com/t/use-ai-results-to-decide-serial-timeout-ranking-results-in-correspondence-games/21932/55

"Where a game would be annulled due to the serial timeout rule, use the AI to check if the timed out person was losing.  If they conclusively were, then award the timeout win to the opponent.  If they were not conclusively winning according to AI, then as before annullment would apply"

**Comment by anoek** [comment]
The problem with not annulling games is that it artificially inflates ranks, as well as sinks the person who timed out into rank oblivion rather quickly, and then they have to crawl their way back up if they end up coming back. We used to see this pretty regularly which is why we started doing the annulment thing. It sucks to annul but the alternative is worse..
