### ISSUE TITLE
WebRTC voice chat

### ISSUE THREAD

**Issue by brylie** [online-go/online-go.com#871]
I am taking online lessons from from an instructor in a different country, via online-go.com. It would be useful, if we could have a voice chat integrated into the OGS chat widget, so we wouldn't have to have third-party chat software.

One approach would be to add a WebRTC option in the private message, for just voice chat.

**Comment by anoek** [comment]
We've actually done this twice and both times it's fallen apart over time because of changes in browsers, and it only ever worked in firefox / chrome since they are the ones that supported webrtc.

Basically, it's more trouble than it's worth. Even when it was working pretty much everyone used discord / twitch anyways so I don't think we'll be implementing this again unless a stable cross platform solution becomes available.
