### ISSUE TITLE
Account-creation vacation-time allotted (too high)

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#912]
**Describe the bug**
New accounts start with 20 days worth of vacation time. 

I propose this be lowered to either 1 or 0, as nobody should really be starting a new account, starting a bunch of games, and then immediately going on a multi-week vacation.

With the proposed change, it would take less than 2 months to accrue a full week of vacation, which seems more than fair.

**To Reproduce**
1. Visit a new account's profile
2. See that they already have 20 days of vacation time

**Expected behavior**
When you start a new job, you need to build up vacation time. I feel it should be the same here.

**Comment by anoek** [comment]
Unless it's been a notable problem I'd rather not change this, if someone is about to go on vacation (or already on vacation!) and they hear about Go and are learning about it, they should be able to sign up, start a game, realize they don't have time right now because they are on vacation, enable vacation mode, and come back to the site once they're back. Unlike starting a new job, Go is not supposed to be a job (for most people) :)
