### ISSUE TITLE
Blocking a player no longer blocks their game chat

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#997]
As reported [here](https://forums.online-go.com/t/chat-bug/23811)  players can now still see their opponent's game chat after they have blocked the opponent.

**Comment by flovo** [comment]
adding `chat-user-${line.user_id}` to `className` in https://github.com/online-go/online-go.com/blob/7e50f8235885eb2ff483fd4587f5707b2fad8e73/src/views/Game/Chat.tsx#L559 should solve this. 

At the moment I don't have the time to find out the details (for example how the `user_id` is named in the line element) and for testing.

**Comment by GreenAsJade** [comment]
@flovo  Can you elaborate a bit on what you are suggesting?   I can't see a `chat-user-xxx` style class, so I feel like I must be mis-interprettting your suggestion.

**Comment by flovo** [comment]
The magic for the `chat-user-xxx`-class happens in java-script, since we have to create the blocked users style class on the fly. The CSS styles are created here:
https://github.com/online-go/online-go.com/blob/41a05c855ea369f5e56c8f459ca7c7612e1e5042/src/components/BlockPlayer/BlockPlayer.ts#L74-L90
This blocking mechanism is site wide. Every element with the `chat-user-xxx`-class is hidden when user_id xxx is blocked. This hasn't to be a chat-line, but can be **every** element on every page of OGS.
